// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: insurance/assign_profile.proto

package insurance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode represents list of errors
type AssignProfileAPIResponseError_ErrorCode int32

const (
	AssignProfileAPIResponseError_ERROR_UNSPECIFIED AssignProfileAPIResponseError_ErrorCode = 0 // Error -> Unspecified.
)

// Enum value maps for AssignProfileAPIResponseError_ErrorCode.
var (
	AssignProfileAPIResponseError_ErrorCode_name = map[int32]string{
		0: "ERROR_UNSPECIFIED",
	}
	AssignProfileAPIResponseError_ErrorCode_value = map[string]int32{
		"ERROR_UNSPECIFIED": 0,
	}
)

func (x AssignProfileAPIResponseError_ErrorCode) Enum() *AssignProfileAPIResponseError_ErrorCode {
	p := new(AssignProfileAPIResponseError_ErrorCode)
	*p = x
	return p
}

func (x AssignProfileAPIResponseError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignProfileAPIResponseError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_insurance_assign_profile_proto_enumTypes[0].Descriptor()
}

func (AssignProfileAPIResponseError_ErrorCode) Type() protoreflect.EnumType {
	return &file_insurance_assign_profile_proto_enumTypes[0]
}

func (x AssignProfileAPIResponseError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignProfileAPIResponseError_ErrorCode.Descriptor instead.
func (AssignProfileAPIResponseError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_insurance_assign_profile_proto_rawDescGZIP(), []int{1, 0}
}

type AssignProfileAPIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignOid *string `protobuf:"bytes,1,opt,name=assign_oid,json=assignOid,proto3,oneof" json:"assign_oid,omitempty"` // when nil, it means clear the OID assigned to the member.
}

func (x *AssignProfileAPIRequest) Reset() {
	*x = AssignProfileAPIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_insurance_assign_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignProfileAPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignProfileAPIRequest) ProtoMessage() {}

func (x *AssignProfileAPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_insurance_assign_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignProfileAPIRequest.ProtoReflect.Descriptor instead.
func (*AssignProfileAPIRequest) Descriptor() ([]byte, []int) {
	return file_insurance_assign_profile_proto_rawDescGZIP(), []int{0}
}

func (x *AssignProfileAPIRequest) GetAssignOid() string {
	if x != nil && x.AssignOid != nil {
		return *x.AssignOid
	}
	return ""
}

// Error represents error resonse of API
type AssignProfileAPIResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    AssignProfileAPIResponseError_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=insurance.AssignProfileAPIResponseError_ErrorCode" json:"code,omitempty"` // Error Code.
	Message string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                   // Error Message.
}

func (x *AssignProfileAPIResponseError) Reset() {
	*x = AssignProfileAPIResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_insurance_assign_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignProfileAPIResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignProfileAPIResponseError) ProtoMessage() {}

func (x *AssignProfileAPIResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_insurance_assign_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignProfileAPIResponseError.ProtoReflect.Descriptor instead.
func (*AssignProfileAPIResponseError) Descriptor() ([]byte, []int) {
	return file_insurance_assign_profile_proto_rawDescGZIP(), []int{1}
}

func (x *AssignProfileAPIResponseError) GetCode() AssignProfileAPIResponseError_ErrorCode {
	if x != nil {
		return x.Code
	}
	return AssignProfileAPIResponseError_ERROR_UNSPECIFIED
}

func (x *AssignProfileAPIResponseError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssignProfileAPIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *AssignProfileAPIResponseError `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *AssignProfileAPIResponse) Reset() {
	*x = AssignProfileAPIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_insurance_assign_profile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignProfileAPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignProfileAPIResponse) ProtoMessage() {}

func (x *AssignProfileAPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_insurance_assign_profile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignProfileAPIResponse.ProtoReflect.Descriptor instead.
func (*AssignProfileAPIResponse) Descriptor() ([]byte, []int) {
	return file_insurance_assign_profile_proto_rawDescGZIP(), []int{2}
}

func (x *AssignProfileAPIResponse) GetError() *AssignProfileAPIResponseError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_insurance_assign_profile_proto protoreflect.FileDescriptor

var file_insurance_assign_profile_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x61, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x4c, 0x0a, 0x17, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x5f, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x4f, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x6f, 0x69, 0x64, 0x22, 0xa5, 0x01, 0x0a, 0x1d, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x41, 0x50, 0x49, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x46, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x69, 0x6e, 0x73, 0x75,
	0x72, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x22, 0x69, 0x0a, 0x18, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x69,
	0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x61, 0x2d, 0x63,
	0x61, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_insurance_assign_profile_proto_rawDescOnce sync.Once
	file_insurance_assign_profile_proto_rawDescData = file_insurance_assign_profile_proto_rawDesc
)

func file_insurance_assign_profile_proto_rawDescGZIP() []byte {
	file_insurance_assign_profile_proto_rawDescOnce.Do(func() {
		file_insurance_assign_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_insurance_assign_profile_proto_rawDescData)
	})
	return file_insurance_assign_profile_proto_rawDescData
}

var file_insurance_assign_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_insurance_assign_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_insurance_assign_profile_proto_goTypes = []interface{}{
	(AssignProfileAPIResponseError_ErrorCode)(0), // 0: insurance.AssignProfileAPIResponseError.ErrorCode
	(*AssignProfileAPIRequest)(nil),              // 1: insurance.AssignProfileAPIRequest
	(*AssignProfileAPIResponseError)(nil),        // 2: insurance.AssignProfileAPIResponseError
	(*AssignProfileAPIResponse)(nil),             // 3: insurance.AssignProfileAPIResponse
}
var file_insurance_assign_profile_proto_depIdxs = []int32{
	0, // 0: insurance.AssignProfileAPIResponseError.code:type_name -> insurance.AssignProfileAPIResponseError.ErrorCode
	2, // 1: insurance.AssignProfileAPIResponse.error:type_name -> insurance.AssignProfileAPIResponseError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_insurance_assign_profile_proto_init() }
func file_insurance_assign_profile_proto_init() {
	if File_insurance_assign_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_insurance_assign_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignProfileAPIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_insurance_assign_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignProfileAPIResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_insurance_assign_profile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignProfileAPIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_insurance_assign_profile_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_insurance_assign_profile_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_insurance_assign_profile_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_insurance_assign_profile_proto_goTypes,
		DependencyIndexes: file_insurance_assign_profile_proto_depIdxs,
		EnumInfos:         file_insurance_assign_profile_proto_enumTypes,
		MessageInfos:      file_insurance_assign_profile_proto_msgTypes,
	}.Build()
	File_insurance_assign_profile_proto = out.File
	file_insurance_assign_profile_proto_rawDesc = nil
	file_insurance_assign_profile_proto_goTypes = nil
	file_insurance_assign_profile_proto_depIdxs = nil
}
