# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insurance/assign_profile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1einsurance/assign_profile.proto\x12\tinsurance\"W\n\x17\x41ssignProfileAPIRequest\x12\x14\n\x0cmember_db_id\x18\x01 \x01(\t\x12\x17\n\nassign_oid\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_assign_oid\"\x96\x01\n\x1d\x41ssignProfileAPIResponseError\x12@\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x32.insurance.AssignProfileAPIResponseError.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\tErrorCode\x12\x15\n\x11\x45RROR_UNSPECIFIED\x10\x00\"b\n\x18\x41ssignProfileAPIResponse\x12<\n\x05\x65rror\x18\x01 \x01(\x0b\x32(.insurance.AssignProfileAPIResponseErrorH\x00\x88\x01\x01\x42\x08\n\x06_errorB2Z0github.com/eka-care/proto-contracts/go/insuranceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'insurance.assign_profile_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/eka-care/proto-contracts/go/insurance'
  _ASSIGNPROFILEAPIREQUEST._serialized_start=45
  _ASSIGNPROFILEAPIREQUEST._serialized_end=132
  _ASSIGNPROFILEAPIRESPONSEERROR._serialized_start=135
  _ASSIGNPROFILEAPIRESPONSEERROR._serialized_end=285
  _ASSIGNPROFILEAPIRESPONSEERROR_ERRORCODE._serialized_start=251
  _ASSIGNPROFILEAPIRESPONSEERROR_ERRORCODE._serialized_end=285
  _ASSIGNPROFILEAPIRESPONSE._serialized_start=287
  _ASSIGNPROFILEAPIRESPONSE._serialized_end=385
# @@protoc_insertion_point(module_scope)
