# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault/cta.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvault/cta.proto\x12\x0cvault.common\x1a\x1cgoogle/protobuf/struct.proto\"\x92\x02\n\x03\x43TA\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12-\n\x06params\x18\x02 \x03(\x0b\x32\x1d.vault.common.CTA.ParamsEntry\x12\x12\n\x05title\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x61\x63tion\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x02id\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x1d\n\x10\x63ta_params_proto\x18\x06 \x01(\tH\x03\x88\x01\x01\x1a\x45\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x42\x08\n\x06_titleB\t\n\x07_actionB\x05\n\x03_idB\x13\n\x11_cta_params_proto\"9\n\tActionCTA\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x12\n\x05title\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_titleB2Z0github.com/eka-care/proto-contracts/go/vault/ctab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault.cta_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/eka-care/proto-contracts/go/vault/cta'
  _CTA_PARAMSENTRY._options = None
  _CTA_PARAMSENTRY._serialized_options = b'8\001'
  _CTA._serialized_start=64
  _CTA._serialized_end=338
  _CTA_PARAMSENTRY._serialized_start=220
  _CTA_PARAMSENTRY._serialized_end=289
  _ACTIONCTA._serialized_start=340
  _ACTIONCTA._serialized_end=397
# @@protoc_insertion_point(module_scope)
