syntax = "proto3";

package vitals;

import "vitals/commons.plots.range.proto";
import "vitals/commons.plots.types.proto";
import "vitals/commons.cta.proto";

option go_package = "github.com/eka-care/device-ingestion/proto-generated/go/vitals/cards/streaks";

/** Streaks cards are used in homepage, to show the latest vitals readings **/
// https://www.figma.com/file/WMYbcRP1whFcA3h3cro9mR/ABHA-%26-Login-2023?type=design&node-id=14369-2221&mode=design&t=aBjWulxjjRO2JT8r-4
message StreaksCardV1 {

  /** Vitals MetaData **/
  StreakCardMetaV1 meta = 1;

  /** Plot Data **/
  StreaksPlotV1 plot = 2;

  /** Latest Reading **/
  LatestReadingV1 latest_reading = 3 [json_name = "latest_reading"];

  /** Bottom Banner **/
  BannerV1 banner = 4;
}

message BannerV1 {
  string title = 1;
  // Icon before the title text.
  string icon = 2;
  // Background color for the banner
  string background_color = 3 [json_name = "background_color"];
  // CTA
  commons.cta.CTAV1 cta = 4;

}

message LatestReadingV1 {
  // Value to be displayed for the latest value
  string value = 1;
  // Unit in string
  string unit = 2;
  // Time in a string format
  string time = 3;
  // State of the reading. High, low normal etc..
  string state_display = 4 [json_name = "state_display"];
  string state_bg_color = 5 [json_name = "state_bg_color"];
  string state_text_color = 6 [json_name = "state_text_color"];

  // Source for the latest reading
  string source_display = 7 [json_name = "source_display"];
  // Source Icon
  string source_icon_url = 8 [json_name = "source_icon_url"];

}


message StreakCardMetaV1 {
  // Icon representing the vital
  string icon = 1;
  // Display text
  string display = 2;
  // CTA
  commons.cta.CTAV1 add_cta = 3 [json_name = "add_cta"];
  // Card state
  CardState card_state = 4 [json_name = "card_state"];

  // values range tab - W / M / Y
  string tab = 5;

  // EKA vital id
  string eka_id = 6 [json_name = "eka_id"];

  /** Main card CTA **/
  commons.cta.CTAV1 card_cta = 7 [json_name = "card_cta"];
}



message StreaksPlotV1 {

  repeated StreaksPlotDataV1 plot_data = 1 [json_name = "plot_data"];
  commons.plots.PlotType type = 2;
  commons.plots.PlotRange plot_range = 3 [json_name = "plot_range"];
}

message StreaksPlotDataV1 {
  string label = 1;

  // String representation of value, might be empty too.
  string value_string = 2 [json_name = "value_string"];

  // Value of the reading.
  optional double value = 3;

  // PLOT_COLUMN_RANGE supports ValueRangeWithAverage
  // Range of the reading
  // One should look at the
  optional commons.plots.ValueRangeWithAverage value_range = 4 [json_name = "value_range"];
}

enum CardState {
  DontUse = 0; // Since in golang with the JSON omitempty the key could get skipped in the generated JSON
  Empty = 1;
  HasData = 2;
}