syntax = "proto3";

package vitals;

import "vitals/commons.cta.proto";
import "vitals/myHealth.home.proto";
option go_package = "github.com/eka-care/device-ingestion/proto-generated/go/vitals/myhealth/add";

message CardDetails {
  SectionType1Cards top = 1;
  optional AutoDetectedComponent auto_detected_details = 2;
  optional HealthBot health_bot = 3;
}

// https://www.figma.com/design/vFAwz8wqE8Qm9MDXJGwixD/ABHA-%26-Login-2024?node-id=6805-232908&t=i1PMsjPhSI4GORxQ-4
message HealthBot {
  // Asthma is a condition.
  string description = 1;

  repeated HealthBotQuestions questions = 3;
}

message HealthBotQuestions {
  string Text = 1;
  commons.cta.CTAV1 cta = 2;
}

message AutoDetectedComponent {
  string title = 1;
  repeated Evidence evidences = 2;
  string sub_title = 3;
}

message Evidence {
  string title = 1;
  string description = 2;
}

message Attributes {
  string title = 1;
  repeated AttributeItem values = 2;
  commons.cta.CTAV1 add_cta = 3;
}

message AttributeItem {
  string title = 1;
}