syntax = "proto3";

package vitals;

option go_package = "github.com/eka-care/device-ingestion/proto-generated/go/vitals/myhealth/add";


// Define an enumeration for different types of health entries.
enum EntryType {
  Unknown = 0;
  Allergies = 1;
  Diagnoses = 2;
}


// Main input message that includes a field for each type of entry.
message AddDataRequest {
  EntryType type = 1; // Type of the entry to determine processing route
  string eka_id = 2; // SNOMED CT identifier for conditions and allergies
  string name = 3; // Name of the condition or allergy
  optional int32 onset_year = 4; // Duration in years since the onset or adoption
}

message AddDataResponse {
  string message = 1;
}
