syntax = "proto3";

package vitals;

option go_package = "github.com/eka-care/device-ingestion/proto-generated/go/vitals";

message VitalsReading {
  optional string test_name = 1;
  optional string test_eka_id = 2;
  optional int32 standalone_reading = 3;
  optional double value = 4;
  optional string value_string = 5;
  optional string unit = 6;
  optional int64 created_at = 7;
  optional string interpretation_eka_id = 8;
  optional int64 document_date = 9;
}

message Readings {
  repeated VitalsReading readings = 1;
}