// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: insurance/insurance.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ErrorCode represents list of errors 
public enum Insurance_ErrorCode: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// Error -> Unspecified.
  case errorUnspecified // = 0
  case UNRECOGNIZED(Int)

  public init() {
    self = .errorUnspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .errorUnspecified
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .errorUnspecified: return 0
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Insurance_ErrorCode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Insurance_ErrorCode] = [
    .errorUnspecified,
  ]
}

#endif  // swift(>=4.2)

public struct Insurance_Insurer {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var img: String = String()

  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _name: String? = nil
}

public struct Insurance_Age {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var age: Int32 = 0

  public var unit: Insurance_Age.Unit = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Unit: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unspecified // = 0
    case year // = 1
    case month // = 2
    case day // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .year
      case 2: self = .month
      case 3: self = .day
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .year: return 1
      case .month: return 2
      case .day: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}
}

#if swift(>=4.2)

extension Insurance_Age.Unit: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Insurance_Age.Unit] = [
    .unspecified,
    .year,
    .month,
    .day,
  ]
}

#endif  // swift(>=4.2)

public struct Insurance_Member {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var age: Insurance_Age {
    get {return _age ?? Insurance_Age()}
    set {_age = newValue}
  }
  /// Returns true if `age` has been explicitly set.
  public var hasAge: Bool {return self._age != nil}
  /// Clears the value of `age`. Subsequent reads from it will return its default value.
  public mutating func clearAge() {self._age = nil}

  public var gender: Insurance_Member.Gender {
    get {return _gender ?? .unspecified}
    set {_gender = newValue}
  }
  /// Returns true if `gender` has been explicitly set.
  public var hasGender: Bool {return self._gender != nil}
  /// Clears the value of `gender`. Subsequent reads from it will return its default value.
  public mutating func clearGender() {self._gender = nil}

  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var dbID: String = String()

  public var pOid: String {
    get {return _pOid ?? String()}
    set {_pOid = newValue}
  }
  /// Returns true if `pOid` has been explicitly set.
  public var hasPOid: Bool {return self._pOid != nil}
  /// Clears the value of `pOid`. Subsequent reads from it will return its default value.
  public mutating func clearPOid() {self._pOid = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Gender: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unspecified // = 0
    case male // = 1
    case female // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .male
      case 2: self = .female
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .male: return 1
      case .female: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _age: Insurance_Age? = nil
  fileprivate var _gender: Insurance_Member.Gender? = nil
  fileprivate var _name: String? = nil
  fileprivate var _id: String? = nil
  fileprivate var _pOid: String? = nil
}

#if swift(>=4.2)

extension Insurance_Member.Gender: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Insurance_Member.Gender] = [
    .unspecified,
    .male,
    .female,
  ]
}

#endif  // swift(>=4.2)

public struct Insurance_PolicyItem {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String = String()

  public var value: String {
    get {return _value ?? String()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {return self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var type: Insurance_PolicyItem.TypeEnum = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TypeEnum: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unspecified // = 0
    case policyType // = 1
    case policyFor // = 2
    case policyNumber // = 3
    case policyEndDate // = 4
    case sumInsured // = 5
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .policyType
      case 2: self = .policyFor
      case 3: self = .policyNumber
      case 4: self = .policyEndDate
      case 5: self = .sumInsured
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .policyType: return 1
      case .policyFor: return 2
      case .policyNumber: return 3
      case .policyEndDate: return 4
      case .sumInsured: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _value: String? = nil
}

#if swift(>=4.2)

extension Insurance_PolicyItem.TypeEnum: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Insurance_PolicyItem.TypeEnum] = [
    .unspecified,
    .policyType,
    .policyFor,
    .policyNumber,
    .policyEndDate,
    .sumInsured,
  ]
}

#endif  // swift(>=4.2)

public struct Insurance_Value {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var val: Int32 = 0

  public var displayValue: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Insurance_SuperTopUpCard {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var title: String = String()

  public var subTitle: String = String()

  public var cta: Vault_Common_CTA {
    get {return _cta ?? Vault_Common_CTA()}
    set {_cta = newValue}
  }
  /// Returns true if `cta` has been explicitly set.
  public var hasCta: Bool {return self._cta != nil}
  /// Clears the value of `cta`. Subsequent reads from it will return its default value.
  public mutating func clearCta() {self._cta = nil}

  public var img: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _cta: Vault_Common_CTA? = nil
}

public struct Insurance_Coverage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var coverageStatus: Insurance_Coverage.CoverageStatus = .unspecified

  public var recommended: Insurance_Value {
    get {return _recommended ?? Insurance_Value()}
    set {_recommended = newValue}
  }
  /// Returns true if `recommended` has been explicitly set.
  public var hasRecommended: Bool {return self._recommended != nil}
  /// Clears the value of `recommended`. Subsequent reads from it will return its default value.
  public mutating func clearRecommended() {self._recommended = nil}

  public var superTopUpCard: Insurance_SuperTopUpCard {
    get {return _superTopUpCard ?? Insurance_SuperTopUpCard()}
    set {_superTopUpCard = newValue}
  }
  /// Returns true if `superTopUpCard` has been explicitly set.
  public var hasSuperTopUpCard: Bool {return self._superTopUpCard != nil}
  /// Clears the value of `superTopUpCard`. Subsequent reads from it will return its default value.
  public mutating func clearSuperTopUpCard() {self._superTopUpCard = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum CoverageStatus: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unspecified // = 0
    case basic // = 1
    case standard // = 2
    case premium // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .basic
      case 2: self = .standard
      case 3: self = .premium
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .basic: return 1
      case .standard: return 2
      case .premium: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _recommended: Insurance_Value? = nil
  fileprivate var _superTopUpCard: Insurance_SuperTopUpCard? = nil
}

#if swift(>=4.2)

extension Insurance_Coverage.CoverageStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Insurance_Coverage.CoverageStatus] = [
    .unspecified,
    .basic,
    .standard,
    .premium,
  ]
}

#endif  // swift(>=4.2)

public struct Insurance_PolicyDetails {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var policyItem: [Insurance_PolicyItem] = []

  public var insuredMembers: [Insurance_Member] = []

  public var sumInsured: Int32 {
    get {return _sumInsured ?? 0}
    set {_sumInsured = newValue}
  }
  /// Returns true if `sumInsured` has been explicitly set.
  public var hasSumInsured: Bool {return self._sumInsured != nil}
  /// Clears the value of `sumInsured`. Subsequent reads from it will return its default value.
  public mutating func clearSumInsured() {self._sumInsured = nil}

  public var policyStatus: Insurance_PolicyDetails.PolicyStatus {
    get {return _policyStatus ?? .unspecified}
    set {_policyStatus = newValue}
  }
  /// Returns true if `policyStatus` has been explicitly set.
  public var hasPolicyStatus: Bool {return self._policyStatus != nil}
  /// Clears the value of `policyStatus`. Subsequent reads from it will return its default value.
  public mutating func clearPolicyStatus() {self._policyStatus = nil}

  public var coverage: Insurance_Coverage {
    get {return _coverage ?? Insurance_Coverage()}
    set {_coverage = newValue}
  }
  /// Returns true if `coverage` has been explicitly set.
  public var hasCoverage: Bool {return self._coverage != nil}
  /// Clears the value of `coverage`. Subsequent reads from it will return its default value.
  public mutating func clearCoverage() {self._coverage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum PolicyStatus: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unspecified // = 0
    case active // = 1
    case inactive // = 2
    case dueSoon // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .inactive
      case 3: self = .dueSoon
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .inactive: return 2
      case .dueSoon: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _sumInsured: Int32? = nil
  fileprivate var _policyStatus: Insurance_PolicyDetails.PolicyStatus? = nil
  fileprivate var _coverage: Insurance_Coverage? = nil
}

#if swift(>=4.2)

extension Insurance_PolicyDetails.PolicyStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static var allCases: [Insurance_PolicyDetails.PolicyStatus] = [
    .unspecified,
    .active,
    .inactive,
    .dueSoon,
  ]
}

#endif  // swift(>=4.2)

public struct Insurance_InsuranceData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var insurer: Insurance_Insurer {
    get {return _storage._insurer ?? Insurance_Insurer()}
    set {_uniqueStorage()._insurer = newValue}
  }
  /// Returns true if `insurer` has been explicitly set.
  public var hasInsurer: Bool {return _storage._insurer != nil}
  /// Clears the value of `insurer`. Subsequent reads from it will return its default value.
  public mutating func clearInsurer() {_uniqueStorage()._insurer = nil}

  public var policyDetails: Insurance_PolicyDetails {
    get {return _storage._policyDetails ?? Insurance_PolicyDetails()}
    set {_uniqueStorage()._policyDetails = newValue}
  }
  /// Returns true if `policyDetails` has been explicitly set.
  public var hasPolicyDetails: Bool {return _storage._policyDetails != nil}
  /// Clears the value of `policyDetails`. Subsequent reads from it will return its default value.
  public mutating func clearPolicyDetails() {_uniqueStorage()._policyDetails = nil}

  public var policyDocumentCta: Vault_Common_CTA {
    get {return _storage._policyDocumentCta ?? Vault_Common_CTA()}
    set {_uniqueStorage()._policyDocumentCta = newValue}
  }
  /// Returns true if `policyDocumentCta` has been explicitly set.
  public var hasPolicyDocumentCta: Bool {return _storage._policyDocumentCta != nil}
  /// Clears the value of `policyDocumentCta`. Subsequent reads from it will return its default value.
  public mutating func clearPolicyDocumentCta() {_uniqueStorage()._policyDocumentCta = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Error represents error resonse of API 
public struct Insurance_Error {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Error Code.
  public var code: Insurance_ErrorCode = .errorUnspecified

  /// Error Message.
  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Insurance_InsuranceAPIResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Insurance_InsuranceAPIResponse.OneOf_Result? = nil

  public var response: Insurance_InsuranceData {
    get {
      if case .response(let v)? = result {return v}
      return Insurance_InsuranceData()
    }
    set {result = .response(newValue)}
  }

  public var error: Insurance_Error {
    get {
      if case .error(let v)? = result {return v}
      return Insurance_Error()
    }
    set {result = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Result: Equatable {
    case response(Insurance_InsuranceData)
    case error(Insurance_Error)

  #if !swift(>=4.1)
    public static func ==(lhs: Insurance_InsuranceAPIResponse.OneOf_Result, rhs: Insurance_InsuranceAPIResponse.OneOf_Result) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.response, .response): return {
        guard case .response(let l) = lhs, case .response(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.error, .error): return {
        guard case .error(let l) = lhs, case .error(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Insurance_ErrorCode: @unchecked Sendable {}
extension Insurance_Insurer: @unchecked Sendable {}
extension Insurance_Age: @unchecked Sendable {}
extension Insurance_Age.Unit: @unchecked Sendable {}
extension Insurance_Member: @unchecked Sendable {}
extension Insurance_Member.Gender: @unchecked Sendable {}
extension Insurance_PolicyItem: @unchecked Sendable {}
extension Insurance_PolicyItem.TypeEnum: @unchecked Sendable {}
extension Insurance_Value: @unchecked Sendable {}
extension Insurance_SuperTopUpCard: @unchecked Sendable {}
extension Insurance_Coverage: @unchecked Sendable {}
extension Insurance_Coverage.CoverageStatus: @unchecked Sendable {}
extension Insurance_PolicyDetails: @unchecked Sendable {}
extension Insurance_PolicyDetails.PolicyStatus: @unchecked Sendable {}
extension Insurance_InsuranceData: @unchecked Sendable {}
extension Insurance_Error: @unchecked Sendable {}
extension Insurance_InsuranceAPIResponse: @unchecked Sendable {}
extension Insurance_InsuranceAPIResponse.OneOf_Result: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "insurance"

extension Insurance_ErrorCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ERROR_UNSPECIFIED"),
  ]
}

extension Insurance_Insurer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Insurer"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "img"),
    2: .same(proto: "name"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.img) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.img.isEmpty {
      try visitor.visitSingularStringField(value: self.img, fieldNumber: 1)
    }
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_Insurer, rhs: Insurance_Insurer) -> Bool {
    if lhs.img != rhs.img {return false}
    if lhs._name != rhs._name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_Age: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Age"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "age"),
    2: .same(proto: "unit"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.age) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.unit) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.age != 0 {
      try visitor.visitSingularInt32Field(value: self.age, fieldNumber: 1)
    }
    if self.unit != .unspecified {
      try visitor.visitSingularEnumField(value: self.unit, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_Age, rhs: Insurance_Age) -> Bool {
    if lhs.age != rhs.age {return false}
    if lhs.unit != rhs.unit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_Age.Unit: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNIT_UNSPECIFIED"),
    1: .same(proto: "UNIT_YEAR"),
    2: .same(proto: "UNIT_MONTH"),
    3: .same(proto: "UNIT_DAY"),
  ]
}

extension Insurance_Member: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Member"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "age"),
    2: .same(proto: "gender"),
    3: .same(proto: "name"),
    4: .same(proto: "id"),
    5: .standard(proto: "db_id"),
    6: .standard(proto: "p_oid"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._age) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._gender) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.dbID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._pOid) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._age {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._gender {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    if !self.dbID.isEmpty {
      try visitor.visitSingularStringField(value: self.dbID, fieldNumber: 5)
    }
    try { if let v = self._pOid {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_Member, rhs: Insurance_Member) -> Bool {
    if lhs._age != rhs._age {return false}
    if lhs._gender != rhs._gender {return false}
    if lhs._name != rhs._name {return false}
    if lhs._id != rhs._id {return false}
    if lhs.dbID != rhs.dbID {return false}
    if lhs._pOid != rhs._pOid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_Member.Gender: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "GENDER_UNSPECIFIED"),
    1: .same(proto: "GENDER_MALE"),
    2: .same(proto: "GENDER_FEMALE"),
  ]
}

extension Insurance_PolicyItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PolicyItem"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "title"),
    2: .same(proto: "value"),
    3: .same(proto: "type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._value) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 1)
    }
    try { if let v = self._value {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if self.type != .unspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_PolicyItem, rhs: Insurance_PolicyItem) -> Bool {
    if lhs.title != rhs.title {return false}
    if lhs._value != rhs._value {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_PolicyItem.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "TYPE_UNSPECIFIED"),
    1: .same(proto: "TYPE_POLICY_TYPE"),
    2: .same(proto: "TYPE_POLICY_FOR"),
    3: .same(proto: "TYPE_POLICY_NUMBER"),
    4: .same(proto: "TYPE_POLICY_END_DATE"),
    5: .same(proto: "TYPE_SUM_INSURED"),
  ]
}

extension Insurance_Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Value"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "val"),
    2: .standard(proto: "display_value"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.val) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayValue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.val != 0 {
      try visitor.visitSingularInt32Field(value: self.val, fieldNumber: 1)
    }
    if !self.displayValue.isEmpty {
      try visitor.visitSingularStringField(value: self.displayValue, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_Value, rhs: Insurance_Value) -> Bool {
    if lhs.val != rhs.val {return false}
    if lhs.displayValue != rhs.displayValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_SuperTopUpCard: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SuperTopUpCard"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "title"),
    2: .standard(proto: "sub_title"),
    3: .same(proto: "cta"),
    4: .same(proto: "img"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.subTitle) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._cta) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.img) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 1)
    }
    if !self.subTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.subTitle, fieldNumber: 2)
    }
    try { if let v = self._cta {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.img.isEmpty {
      try visitor.visitSingularStringField(value: self.img, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_SuperTopUpCard, rhs: Insurance_SuperTopUpCard) -> Bool {
    if lhs.title != rhs.title {return false}
    if lhs.subTitle != rhs.subTitle {return false}
    if lhs._cta != rhs._cta {return false}
    if lhs.img != rhs.img {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_Coverage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Coverage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "coverage_status"),
    2: .same(proto: "recommended"),
    3: .standard(proto: "super_top_up_card"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.coverageStatus) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._recommended) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._superTopUpCard) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.coverageStatus != .unspecified {
      try visitor.visitSingularEnumField(value: self.coverageStatus, fieldNumber: 1)
    }
    try { if let v = self._recommended {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._superTopUpCard {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_Coverage, rhs: Insurance_Coverage) -> Bool {
    if lhs.coverageStatus != rhs.coverageStatus {return false}
    if lhs._recommended != rhs._recommended {return false}
    if lhs._superTopUpCard != rhs._superTopUpCard {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_Coverage.CoverageStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "COVERAGE_STATUS_UNSPECIFIED"),
    1: .same(proto: "COVERAGE_STATUS_BASIC"),
    2: .same(proto: "COVERAGE_STATUS_STANDARD"),
    3: .same(proto: "COVERAGE_STATUS_PREMIUM"),
  ]
}

extension Insurance_PolicyDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PolicyDetails"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "policy_item"),
    2: .standard(proto: "insured_members"),
    3: .standard(proto: "sum_insured"),
    4: .standard(proto: "policy_status"),
    5: .same(proto: "coverage"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.policyItem) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.insuredMembers) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._sumInsured) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._policyStatus) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._coverage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.policyItem.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.policyItem, fieldNumber: 1)
    }
    if !self.insuredMembers.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.insuredMembers, fieldNumber: 2)
    }
    try { if let v = self._sumInsured {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._policyStatus {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._coverage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_PolicyDetails, rhs: Insurance_PolicyDetails) -> Bool {
    if lhs.policyItem != rhs.policyItem {return false}
    if lhs.insuredMembers != rhs.insuredMembers {return false}
    if lhs._sumInsured != rhs._sumInsured {return false}
    if lhs._policyStatus != rhs._policyStatus {return false}
    if lhs._coverage != rhs._coverage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_PolicyDetails.PolicyStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "POLICY_STATUS_UNSPECIFIED"),
    1: .same(proto: "POLICY_STATUS_ACTIVE"),
    2: .same(proto: "POLICY_STATUS_INACTIVE"),
    3: .same(proto: "POLICY_STATUS_DUE_SOON"),
  ]
}

extension Insurance_InsuranceData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InsuranceData"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "insurer"),
    2: .standard(proto: "policy_details"),
    3: .standard(proto: "policy_document_cta"),
  ]

  fileprivate class _StorageClass {
    var _insurer: Insurance_Insurer? = nil
    var _policyDetails: Insurance_PolicyDetails? = nil
    var _policyDocumentCta: Vault_Common_CTA? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _insurer = source._insurer
      _policyDetails = source._policyDetails
      _policyDocumentCta = source._policyDocumentCta
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._insurer) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._policyDetails) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._policyDocumentCta) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._insurer {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._policyDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._policyDocumentCta {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_InsuranceData, rhs: Insurance_InsuranceData) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._insurer != rhs_storage._insurer {return false}
        if _storage._policyDetails != rhs_storage._policyDetails {return false}
        if _storage._policyDocumentCta != rhs_storage._policyDocumentCta {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_Error: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Error"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
    2: .same(proto: "message"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .errorUnspecified {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_Error, rhs: Insurance_Error) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_InsuranceAPIResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InsuranceAPIResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "response"),
    2: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Insurance_InsuranceData?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .response(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .response(v)
        }
      }()
      case 2: try {
        var v: Insurance_Error?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .error(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .response?: try {
      guard case .response(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_InsuranceAPIResponse, rhs: Insurance_InsuranceAPIResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
