// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: insurance/insurance_summary.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Insurance_CoverageInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var startValue: Insurance_Value {
    get {return _startValue ?? Insurance_Value()}
    set {_startValue = newValue}
  }
  /// Returns true if `startValue` has been explicitly set.
  public var hasStartValue: Bool {return self._startValue != nil}
  /// Clears the value of `startValue`. Subsequent reads from it will return its default value.
  public mutating func clearStartValue() {self._startValue = nil}

  public var endValue: Insurance_Value {
    get {return _endValue ?? Insurance_Value()}
    set {_endValue = newValue}
  }
  /// Returns true if `endValue` has been explicitly set.
  public var hasEndValue: Bool {return self._endValue != nil}
  /// Clears the value of `endValue`. Subsequent reads from it will return its default value.
  public mutating func clearEndValue() {self._endValue = nil}

  public var type: Insurance_CoverageInfo.TypeEnum = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TypeEnum: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case unspecified // = 0
    case base // = 1
    case superTopUp // = 2
    case missing // = 3
    case recommended // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .base
      case 2: self = .superTopUp
      case 3: self = .missing
      case 4: self = .recommended
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .base: return 1
      case .superTopUp: return 2
      case .missing: return 3
      case .recommended: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}

  fileprivate var _startValue: Insurance_Value? = nil
  fileprivate var _endValue: Insurance_Value? = nil
}

#if swift(>=4.2)

extension Insurance_CoverageInfo.TypeEnum: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Insurance_CoverageInfo.TypeEnum] = [
    .unspecified,
    .base,
    .superTopUp,
    .missing,
    .recommended,
  ]
}

#endif  // swift(>=4.2)

public struct Insurance_PoliciesSummary {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var totalCoverage: Insurance_Value {
    get {return _storage._totalCoverage ?? Insurance_Value()}
    set {_uniqueStorage()._totalCoverage = newValue}
  }
  /// Returns true if `totalCoverage` has been explicitly set.
  public var hasTotalCoverage: Bool {return _storage._totalCoverage != nil}
  /// Clears the value of `totalCoverage`. Subsequent reads from it will return its default value.
  public mutating func clearTotalCoverage() {_uniqueStorage()._totalCoverage = nil}

  public var totalPremium: Insurance_ValueFloat {
    get {return _storage._totalPremium ?? Insurance_ValueFloat()}
    set {_uniqueStorage()._totalPremium = newValue}
  }
  /// Returns true if `totalPremium` has been explicitly set.
  public var hasTotalPremium: Bool {return _storage._totalPremium != nil}
  /// Clears the value of `totalPremium`. Subsequent reads from it will return its default value.
  public mutating func clearTotalPremium() {_uniqueStorage()._totalPremium = nil}

  public var coverageInfo: Insurance_PoliciesSummary.CoverageDetails {
    get {return _storage._coverageInfo ?? Insurance_PoliciesSummary.CoverageDetails()}
    set {_uniqueStorage()._coverageInfo = newValue}
  }
  /// Returns true if `coverageInfo` has been explicitly set.
  public var hasCoverageInfo: Bool {return _storage._coverageInfo != nil}
  /// Clears the value of `coverageInfo`. Subsequent reads from it will return its default value.
  public mutating func clearCoverageInfo() {_uniqueStorage()._coverageInfo = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct CoverageDetails {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var coverage: Insurance_Coverage {
      get {return _coverage ?? Insurance_Coverage()}
      set {_coverage = newValue}
    }
    /// Returns true if `coverage` has been explicitly set.
    public var hasCoverage: Bool {return self._coverage != nil}
    /// Clears the value of `coverage`. Subsequent reads from it will return its default value.
    public mutating func clearCoverage() {self._coverage = nil}

    public var breakup: [Insurance_CoverageInfo] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _coverage: Insurance_Coverage? = nil
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Insurance_Policy {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var insurer: Insurance_InsurerInfo {
    get {return _insurer ?? Insurance_InsurerInfo()}
    set {_insurer = newValue}
  }
  /// Returns true if `insurer` has been explicitly set.
  public var hasInsurer: Bool {return self._insurer != nil}
  /// Clears the value of `insurer`. Subsequent reads from it will return its default value.
  public mutating func clearInsurer() {self._insurer = nil}

  public var policyDetails: Insurance_PolicyDetails {
    get {return _policyDetails ?? Insurance_PolicyDetails()}
    set {_policyDetails = newValue}
  }
  /// Returns true if `policyDetails` has been explicitly set.
  public var hasPolicyDetails: Bool {return self._policyDetails != nil}
  /// Clears the value of `policyDetails`. Subsequent reads from it will return its default value.
  public mutating func clearPolicyDetails() {self._policyDetails = nil}

  public var cta: Vault_Common_CTA {
    get {return _cta ?? Vault_Common_CTA()}
    set {_cta = newValue}
  }
  /// Returns true if `cta` has been explicitly set.
  public var hasCta: Bool {return self._cta != nil}
  /// Clears the value of `cta`. Subsequent reads from it will return its default value.
  public mutating func clearCta() {self._cta = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _insurer: Insurance_InsurerInfo? = nil
  fileprivate var _policyDetails: Insurance_PolicyDetails? = nil
  fileprivate var _cta: Vault_Common_CTA? = nil
}

public struct Insurance_InsuranceSummaryData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var policiesSummary: Insurance_PoliciesSummary {
    get {return _policiesSummary ?? Insurance_PoliciesSummary()}
    set {_policiesSummary = newValue}
  }
  /// Returns true if `policiesSummary` has been explicitly set.
  public var hasPoliciesSummary: Bool {return self._policiesSummary != nil}
  /// Clears the value of `policiesSummary`. Subsequent reads from it will return its default value.
  public mutating func clearPoliciesSummary() {self._policiesSummary = nil}

  public var policies: [Insurance_Policy] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _policiesSummary: Insurance_PoliciesSummary? = nil
}

public struct Insurance_InsuranceSummaryAPIResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Insurance_InsuranceSummaryAPIResponse.OneOf_Result? = nil

  public var response: Insurance_InsuranceSummaryData {
    get {
      if case .response(let v)? = result {return v}
      return Insurance_InsuranceSummaryData()
    }
    set {result = .response(newValue)}
  }

  public var error: Insurance_InsuranceSummaryAPIResponse.Error {
    get {
      if case .error(let v)? = result {return v}
      return Insurance_InsuranceSummaryAPIResponse.Error()
    }
    set {result = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Result: Equatable {
    case response(Insurance_InsuranceSummaryData)
    case error(Insurance_InsuranceSummaryAPIResponse.Error)

  #if !swift(>=4.1)
    public static func ==(lhs: Insurance_InsuranceSummaryAPIResponse.OneOf_Result, rhs: Insurance_InsuranceSummaryAPIResponse.OneOf_Result) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.response, .response): return {
        guard case .response(let l) = lhs, case .response(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.error, .error): return {
        guard case .error(let l) = lhs, case .error(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  /// ErrorCode represents list of errors 
  public enum ErrorCode: SwiftProtobuf.Enum {
    public typealias RawValue = Int

    /// Error -> Unspecified.
    case errorUnspecified // = 0
    case UNRECOGNIZED(Int)

    public init() {
      self = .errorUnspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .errorUnspecified
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .errorUnspecified: return 0
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  /// Error represents error resonse of API 
  public struct Error {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Error Code.
    public var code: Insurance_InsuranceSummaryAPIResponse.ErrorCode = .errorUnspecified

    /// Error Message.
    public var message: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

#if swift(>=4.2)

extension Insurance_InsuranceSummaryAPIResponse.ErrorCode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Insurance_InsuranceSummaryAPIResponse.ErrorCode] = [
    .errorUnspecified,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Insurance_CoverageInfo: @unchecked Sendable {}
extension Insurance_CoverageInfo.TypeEnum: @unchecked Sendable {}
extension Insurance_PoliciesSummary: @unchecked Sendable {}
extension Insurance_PoliciesSummary.CoverageDetails: @unchecked Sendable {}
extension Insurance_Policy: @unchecked Sendable {}
extension Insurance_InsuranceSummaryData: @unchecked Sendable {}
extension Insurance_InsuranceSummaryAPIResponse: @unchecked Sendable {}
extension Insurance_InsuranceSummaryAPIResponse.OneOf_Result: @unchecked Sendable {}
extension Insurance_InsuranceSummaryAPIResponse.ErrorCode: @unchecked Sendable {}
extension Insurance_InsuranceSummaryAPIResponse.Error: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "insurance"

extension Insurance_CoverageInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CoverageInfo"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "start_value"),
    2: .standard(proto: "end_value"),
    3: .same(proto: "type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._startValue) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._endValue) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._startValue {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._endValue {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.type != .unspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_CoverageInfo, rhs: Insurance_CoverageInfo) -> Bool {
    if lhs._startValue != rhs._startValue {return false}
    if lhs._endValue != rhs._endValue {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_CoverageInfo.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "TYPE_UNSPECIFIED"),
    1: .same(proto: "TYPE_BASE"),
    2: .same(proto: "TYPE_SUPER_TOP_UP"),
    3: .same(proto: "TYPE_MISSING"),
    4: .same(proto: "TYPE_RECOMMENDED"),
  ]
}

extension Insurance_PoliciesSummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PoliciesSummary"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "total_coverage"),
    2: .standard(proto: "total_premium"),
    3: .standard(proto: "coverage_info"),
  ]

  fileprivate class _StorageClass {
    var _totalCoverage: Insurance_Value? = nil
    var _totalPremium: Insurance_ValueFloat? = nil
    var _coverageInfo: Insurance_PoliciesSummary.CoverageDetails? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _totalCoverage = source._totalCoverage
      _totalPremium = source._totalPremium
      _coverageInfo = source._coverageInfo
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._totalCoverage) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._totalPremium) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._coverageInfo) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._totalCoverage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._totalPremium {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._coverageInfo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_PoliciesSummary, rhs: Insurance_PoliciesSummary) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._totalCoverage != rhs_storage._totalCoverage {return false}
        if _storage._totalPremium != rhs_storage._totalPremium {return false}
        if _storage._coverageInfo != rhs_storage._coverageInfo {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_PoliciesSummary.CoverageDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Insurance_PoliciesSummary.protoMessageName + ".CoverageDetails"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "coverage"),
    2: .same(proto: "breakup"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._coverage) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.breakup) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._coverage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.breakup.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.breakup, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_PoliciesSummary.CoverageDetails, rhs: Insurance_PoliciesSummary.CoverageDetails) -> Bool {
    if lhs._coverage != rhs._coverage {return false}
    if lhs.breakup != rhs.breakup {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_Policy: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Policy"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "insurer"),
    2: .standard(proto: "policy_details"),
    3: .same(proto: "cta"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._insurer) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._policyDetails) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._cta) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._insurer {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._policyDetails {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._cta {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_Policy, rhs: Insurance_Policy) -> Bool {
    if lhs._insurer != rhs._insurer {return false}
    if lhs._policyDetails != rhs._policyDetails {return false}
    if lhs._cta != rhs._cta {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_InsuranceSummaryData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InsuranceSummaryData"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "policies_summary"),
    2: .same(proto: "policies"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._policiesSummary) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.policies) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._policiesSummary {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.policies.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.policies, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_InsuranceSummaryData, rhs: Insurance_InsuranceSummaryData) -> Bool {
    if lhs._policiesSummary != rhs._policiesSummary {return false}
    if lhs.policies != rhs.policies {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_InsuranceSummaryAPIResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InsuranceSummaryAPIResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "response"),
    2: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Insurance_InsuranceSummaryData?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .response(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .response(v)
        }
      }()
      case 2: try {
        var v: Insurance_InsuranceSummaryAPIResponse.Error?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .error(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .response?: try {
      guard case .response(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_InsuranceSummaryAPIResponse, rhs: Insurance_InsuranceSummaryAPIResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_InsuranceSummaryAPIResponse.ErrorCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ERROR_UNSPECIFIED"),
  ]
}

extension Insurance_InsuranceSummaryAPIResponse.Error: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Insurance_InsuranceSummaryAPIResponse.protoMessageName + ".Error"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
    2: .same(proto: "message"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .errorUnspecified {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_InsuranceSummaryAPIResponse.Error, rhs: Insurance_InsuranceSummaryAPIResponse.Error) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
