// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.28.2
// source: vault/banner_body_parameter.proto

package bannerbodyparameter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BannerBodyParameter is an enum used to represent dynamic parameter.
type BannerBodyParameter int32

const (
	BannerBodyParameter_BODY_PARAMETER_UNSPECIFIED BannerBodyParameter = 0 // Unhandled dynamic parameter.
	BannerBodyParameter_BODY_PARAMETER_MOBILE      BannerBodyParameter = 1 // Mobile number dynamic parameter.
)

// Enum value maps for BannerBodyParameter.
var (
	BannerBodyParameter_name = map[int32]string{
		0: "BODY_PARAMETER_UNSPECIFIED",
		1: "BODY_PARAMETER_MOBILE",
	}
	BannerBodyParameter_value = map[string]int32{
		"BODY_PARAMETER_UNSPECIFIED": 0,
		"BODY_PARAMETER_MOBILE":      1,
	}
)

func (x BannerBodyParameter) Enum() *BannerBodyParameter {
	p := new(BannerBodyParameter)
	*p = x
	return p
}

func (x BannerBodyParameter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BannerBodyParameter) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_banner_body_parameter_proto_enumTypes[0].Descriptor()
}

func (BannerBodyParameter) Type() protoreflect.EnumType {
	return &file_vault_banner_body_parameter_proto_enumTypes[0]
}

func (x BannerBodyParameter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BannerBodyParameter.Descriptor instead.
func (BannerBodyParameter) EnumDescriptor() ([]byte, []int) {
	return file_vault_banner_body_parameter_proto_rawDescGZIP(), []int{0}
}

var File_vault_banner_body_parameter_proto protoreflect.FileDescriptor

var file_vault_banner_body_parameter_proto_rawDesc = []byte{
	0x0a, 0x21, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x62,
	0x6f, 0x64, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x2a, 0x50, 0x0a, 0x13, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x6f, 0x64, 0x79, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x1a, 0x42, 0x4f, 0x44, 0x59, 0x5f,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x4f, 0x44, 0x59, 0x5f,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45,
	0x10, 0x01, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x6b, 0x61, 0x2d, 0x63, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x62, 0x6f, 0x64, 0x79, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vault_banner_body_parameter_proto_rawDescOnce sync.Once
	file_vault_banner_body_parameter_proto_rawDescData = file_vault_banner_body_parameter_proto_rawDesc
)

func file_vault_banner_body_parameter_proto_rawDescGZIP() []byte {
	file_vault_banner_body_parameter_proto_rawDescOnce.Do(func() {
		file_vault_banner_body_parameter_proto_rawDescData = protoimpl.X.CompressGZIP(file_vault_banner_body_parameter_proto_rawDescData)
	})
	return file_vault_banner_body_parameter_proto_rawDescData
}

var file_vault_banner_body_parameter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vault_banner_body_parameter_proto_goTypes = []interface{}{
	(BannerBodyParameter)(0), // 0: vault.banner_body_parameter.BannerBodyParameter
}
var file_vault_banner_body_parameter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vault_banner_body_parameter_proto_init() }
func file_vault_banner_body_parameter_proto_init() {
	if File_vault_banner_body_parameter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vault_banner_body_parameter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vault_banner_body_parameter_proto_goTypes,
		DependencyIndexes: file_vault_banner_body_parameter_proto_depIdxs,
		EnumInfos:         file_vault_banner_body_parameter_proto_enumTypes,
	}.Build()
	File_vault_banner_body_parameter_proto = out.File
	file_vault_banner_body_parameter_proto_rawDesc = nil
	file_vault_banner_body_parameter_proto_goTypes = nil
	file_vault_banner_body_parameter_proto_depIdxs = nil
}
