syntax = "proto3";

package auth;

option go_package = "github.com/eka-care/aorta-go/proto-generated/go/auth";
import "auth/auth.aenums.proto";
import "auth/auth.common.proto";

message AuthVerifyRequest {
  string txn_id = 1;
  // For EmailOtp and MobileOtp, it will be the OTP.
  // For Google and Apple, it will be the token.
  string code = 2;
  optional AuthSkipStates skip_state = 3;
}


message AuthVerifyResponse {
  string txn_id = 1;

  AuthSkipStates skip_state = 2;
  AuthMethod method = 3;
  // Will be present only if skipState is SkipStateErrored.
  optional AuthError error = 4;

  // Data will be present only if skipState is SkipStateEnd.
  optional Data data = 5;
}
