syntax = "proto3";

package auth;

option go_package = "github.com/eka-care/aorta-go/proto-generated/go/auth";
import "auth/auth.aenums.proto";
import "auth/auth.common.proto";

message LinkMobileInit {
  string mobile = 1;
  string txn_id = 2;
}


message LinkMobileInitResp {
  string txn_id = 1;

  AuthSkipStates skip_state = 2;

  // Will be present only if skipState is SkipStateErrored.
  optional AuthError error = 3;

  // Data will be present only if skipState is SkipStateEnd.
  optional Data data = 4;
}

message LinkMobileVerify {
  string txn_id = 1;
  string otp = 2;

}

message LinkMobileVerifyResp {
  string txnId = 1;
  AuthSkipStates skip_state = 2;

  // Will be present only if skipState is SkipStateErrored.
  optional AuthError error = 3;
  // Data will be present only if skipState is SkipStateEnd.
  optional Data data = 4;
}