syntax = "proto3";

package auth;

option go_package = "github.com/eka-care/aorta-go/proto-generated/go/auth";
import "auth/auth.aenums.proto";
import "auth/auth.common.proto";
import "google/protobuf/timestamp.proto";

message AuthInit {
  AuthMethod method = 1;
  string identifier = 2;
  // Will be the email id for EmailOtp, mobile number for MobileOtp.
  // For Google and Apple, it will be None.
  optional Attributes attributes = 3;
}

message Attributes {
  optional bool allow_whatsapp = 1;
  optional bool allow_email = 2;
}

message AuthInitResponse {
  string txn_id = 1;
  string message = 2;
  optional AuthError error = 3;
  optional OtpInitResponse otp = 4;
}

message OtpInitResponse {
  bool triggered = 1;
  int64 retries = 2 ;
  string  nextOtpRequest = 4 ;
}
