syntax = "proto3";
package auth;

option go_package = "github.com/eka-care/aorta-go/proto-generated/go/auth";

message AuthError {
  string code = 1;
  string message = 2;
}

message Tokens {
  // JWT Token for the user
  string sess = 1;
  // Refresh token for the user
  string refresh = 2;
}

message ExternalTokens {
  string firebase = 1 ;
}

message Params {
  optional string url = 1;
}

message Target {
  optional string pid = 1;
  optional string pageId = 2;
  optional Params params = 3;
}

message Data {
  Tokens tokens = 1;
  ExternalTokens external_tokens = 2;
  // This will be present only if the user is old and will be Type1 profile.
  optional Profile profile = 3;
  optional bool has_more_profiles = 4;
  optional bool first_time_user = 5;
  optional Target tgt = 6;
}

message Profile {
  string fln = 1;
  string fn = 2;
  optional string mn = 3;
  optional string ln = 4;
  string gen = 5;
  string dob = 6;
  optional string mobile = 7;
  optional string email = 8;
  string uuid = 9;
  optional string bloodgroup = 10;
  optional string pic = 11;
  optional string as = 12;
  // @gotags: json:"is-d,omitempty"
  optional bool is_d = 13 [json_name = "is-d"];
  // @gotags: json:"is-d-s,omitempty"
  optional bool is_d_s = 14 [json_name = "is-d-s"];
  // @gotags: json:"is-p,omitempty"
  optional bool is_p = 15 [json_name = "is-p"];
  // @gotags: json:"is-biz,omitempty"
  optional bool is_biz = 16 [json_name = "is-biz"];
  string oid = 17;
  int64 type = 18;
  // @gotags: json:"health-ids,omitempty"
  repeated string health_ids = 19 [json_name = "health-ids"];
  // @gotags: json:"at,omitempty"
  optional   string created_at = 20 [json_name = "at"];
  optional string pincode = 21;
  // @gotags: json:"dob-valid,omitempty"
  optional bool dob_valid = 22 [json_name = "dob-valid"];
}

message Attributes {
  optional bool allow_whatsapp = 1;
  optional bool allow_email = 2;
}

message Profiles {
  repeated Profile data = 1;
}