syntax = "proto3";

package auth;

option go_package = "github.com/eka-care/aorta-go/proto-generated/go/auth";
import "auth/auth.aenums.proto";
import "auth/auth.common.proto";

message LoginRequest {
  AuthMethod method = 1;
  string identifier = 2;
  string code = 3;
  optional Attributes attributes = 4;
}

message LoginResponse {
  AuthSkipStates skip_state = 1;
  AuthMethod method = 2;
  // Will be present only if skipState is SkipStateErrored.
  optional AuthError error = 3;

  // Data will be present only if skipState is SkipStateEnd.
  optional Data data = 4;
}