// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: vault/document_status.proto

package docstatus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentStatus represents status of given document id list.
type DocumentStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to DocumentStatusResponse:
	//
	//	*DocumentStatus_DocumentAccessibleInfo
	//	*DocumentStatus_DocumentInfo
	DocumentStatusResponse isDocumentStatus_DocumentStatusResponse `protobuf_oneof:"DocumentStatusResponse"`
}

func (x *DocumentStatus) Reset() {
	*x = DocumentStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_document_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentStatus) ProtoMessage() {}

func (x *DocumentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vault_document_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentStatus.ProtoReflect.Descriptor instead.
func (*DocumentStatus) Descriptor() ([]byte, []int) {
	return file_vault_document_status_proto_rawDescGZIP(), []int{0}
}

func (m *DocumentStatus) GetDocumentStatusResponse() isDocumentStatus_DocumentStatusResponse {
	if m != nil {
		return m.DocumentStatusResponse
	}
	return nil
}

func (x *DocumentStatus) GetDocumentAccessibleInfo() *DocumentAccessible {
	if x, ok := x.GetDocumentStatusResponse().(*DocumentStatus_DocumentAccessibleInfo); ok {
		return x.DocumentAccessibleInfo
	}
	return nil
}

func (x *DocumentStatus) GetDocumentInfo() *DocumentInfo {
	if x, ok := x.GetDocumentStatusResponse().(*DocumentStatus_DocumentInfo); ok {
		return x.DocumentInfo
	}
	return nil
}

type isDocumentStatus_DocumentStatusResponse interface {
	isDocumentStatus_DocumentStatusResponse()
}

type DocumentStatus_DocumentAccessibleInfo struct {
	DocumentAccessibleInfo *DocumentAccessible `protobuf:"bytes,1,opt,name=document_accessible_info,json=documentAccessibleInfo,proto3,oneof"` // DocumentAccessible represent document
}

type DocumentStatus_DocumentInfo struct {
	// upload status and related fields.
	DocumentInfo *DocumentInfo `protobuf:"bytes,2,opt,name=document_info,json=documentInfo,proto3,oneof"` // DocumentInfo represents document related other info.
}

func (*DocumentStatus_DocumentAccessibleInfo) isDocumentStatus_DocumentStatusResponse() {}

func (*DocumentStatus_DocumentInfo) isDocumentStatus_DocumentStatusResponse() {}

// DocumentListResponse represents response for the list of documents in processing.
type DocumentListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentStatus []*DocumentStatus `protobuf:"bytes,1,rep,name=document_status,json=documentStatus,proto3" json:"document_status,omitempty"` // Status of requested document ids.
}

func (x *DocumentListResponse) Reset() {
	*x = DocumentListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_document_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentListResponse) ProtoMessage() {}

func (x *DocumentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_document_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentListResponse.ProtoReflect.Descriptor instead.
func (*DocumentListResponse) Descriptor() ([]byte, []int) {
	return file_vault_document_status_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentListResponse) GetDocumentStatus() []*DocumentStatus {
	if x != nil {
		return x.DocumentStatus
	}
	return nil
}

// DocumentSmartReport represents smart report status
type DocumentSmartReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAnalyzing            bool    `protobuf:"varint,1,opt,name=is_analyzing,json=isAnalyzing,proto3" json:"is_analyzing,omitempty"`                                      // Represents if document is in processing.
	IsSmartReportAvailable bool    `protobuf:"varint,2,opt,name=is_smart_report_available,json=isSmartReportAvailable,proto3" json:"is_smart_report_available,omitempty"` // Represents if document is a smart report.
	DocumentDate           *string `protobuf:"bytes,3,opt,name=document_date,json=documentDate,proto3,oneof" json:"document_date,omitempty"`                              // Date of the document (lab report, prescription).
}

func (x *DocumentSmartReport) Reset() {
	*x = DocumentSmartReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_document_status_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentSmartReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSmartReport) ProtoMessage() {}

func (x *DocumentSmartReport) ProtoReflect() protoreflect.Message {
	mi := &file_vault_document_status_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSmartReport.ProtoReflect.Descriptor instead.
func (*DocumentSmartReport) Descriptor() ([]byte, []int) {
	return file_vault_document_status_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentSmartReport) GetIsAnalyzing() bool {
	if x != nil {
		return x.IsAnalyzing
	}
	return false
}

func (x *DocumentSmartReport) GetIsSmartReportAvailable() bool {
	if x != nil {
		return x.IsSmartReportAvailable
	}
	return false
}

func (x *DocumentSmartReport) GetDocumentDate() string {
	if x != nil && x.DocumentDate != nil {
		return *x.DocumentDate
	}
	return ""
}

// DocumentInfo represents document related other info.
type DocumentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thumbnail                *string  `protobuf:"bytes,1,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`                                                                 // Thumbnail of the lab report.
	PatientId                *string  `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3,oneof" json:"patient_id,omitempty"`                                                // OID of the patient on document.
	Tags                     []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                 // Derived tags of the document.
	PostAnalyzerObservations *string  `protobuf:"bytes,4,opt,name=post_analyzer_observations,json=postAnalyzerObservations,proto3,oneof" json:"post_analyzer_observations,omitempty"` // Confirm the scanned data message.
}

func (x *DocumentInfo) Reset() {
	*x = DocumentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_document_status_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentInfo) ProtoMessage() {}

func (x *DocumentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vault_document_status_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentInfo.ProtoReflect.Descriptor instead.
func (*DocumentInfo) Descriptor() ([]byte, []int) {
	return file_vault_document_status_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentInfo) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *DocumentInfo) GetPatientId() string {
	if x != nil && x.PatientId != nil {
		return *x.PatientId
	}
	return ""
}

func (x *DocumentInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DocumentInfo) GetPostAnalyzerObservations() string {
	if x != nil && x.PostAnalyzerObservations != nil {
		return *x.PostAnalyzerObservations
	}
	return ""
}

// DocumentAccessible represents if document is uploaded to server and processing of it.
type DocumentAccessible struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAccessible        bool                 `protobuf:"varint,1,opt,name=is_accessible,json=isAccessible,proto3" json:"is_accessible,omitempty"`                       // Is_accessible represents if document is uploaded to server or not.
	DocumentSmartReport *DocumentSmartReport `protobuf:"bytes,2,opt,name=document_smart_report,json=documentSmartReport,proto3" json:"document_smart_report,omitempty"` // DocumentSmartReport represent smart report related status of document.
	DocumentInfo        *DocumentInfo        `protobuf:"bytes,3,opt,name=document_info,json=documentInfo,proto3" json:"document_info,omitempty"`                        // Document related other info.
}

func (x *DocumentAccessible) Reset() {
	*x = DocumentAccessible{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_document_status_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentAccessible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentAccessible) ProtoMessage() {}

func (x *DocumentAccessible) ProtoReflect() protoreflect.Message {
	mi := &file_vault_document_status_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentAccessible.ProtoReflect.Descriptor instead.
func (*DocumentAccessible) Descriptor() ([]byte, []int) {
	return file_vault_document_status_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentAccessible) GetIsAccessible() bool {
	if x != nil {
		return x.IsAccessible
	}
	return false
}

func (x *DocumentAccessible) GetDocumentSmartReport() *DocumentSmartReport {
	if x != nil {
		return x.DocumentSmartReport
	}
	return nil
}

func (x *DocumentAccessible) GetDocumentInfo() *DocumentInfo {
	if x != nil {
		return x.DocumentInfo
	}
	return nil
}

// DocumentListRequest represents list of document ids for request body.
type DocumentListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []string `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"` // List of document ids.
}

func (x *DocumentListRequest) Reset() {
	*x = DocumentListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_document_status_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentListRequest) ProtoMessage() {}

func (x *DocumentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_document_status_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentListRequest.ProtoReflect.Descriptor instead.
func (*DocumentListRequest) Descriptor() ([]byte, []int) {
	return file_vault_document_status_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentListRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_vault_document_status_proto protoreflect.FileDescriptor

var file_vault_document_status_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x76,
	0x61, 0x75, 0x6c, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0xd3, 0x01, 0x0a, 0x0e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x60, 0x0a, 0x18, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x64, 0x6f, 0x63,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x16, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x45, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0c, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x18, 0x0a, 0x16, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x61, 0x0a, 0x14, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a,
	0x0f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x64,
	0x6f, 0x63, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xaf, 0x01, 0x0a, 0x13, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a,
	0x69, 0x6e, 0x67, 0x12, 0x39, 0x0a, 0x19, 0x69, 0x73, 0x5f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x69, 0x73, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28,
	0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x22, 0xe8, 0x01, 0x0a, 0x0c, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x09, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x22,
	0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x41, 0x0a, 0x1a, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x18, 0x70, 0x6f,
	0x73, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x68,
	0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x1d, 0x0a, 0x1b, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xd9, 0x01, 0x0a, 0x12, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x69, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x12, 0x59, 0x0a, 0x15, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x6d,
	0x61, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x6d, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x13, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x43, 0x0a, 0x0d,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x33, 0x0a, 0x13, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x61, 0x2d, 0x63, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x67, 0x6f,
	0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vault_document_status_proto_rawDescOnce sync.Once
	file_vault_document_status_proto_rawDescData = file_vault_document_status_proto_rawDesc
)

func file_vault_document_status_proto_rawDescGZIP() []byte {
	file_vault_document_status_proto_rawDescOnce.Do(func() {
		file_vault_document_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_vault_document_status_proto_rawDescData)
	})
	return file_vault_document_status_proto_rawDescData
}

var file_vault_document_status_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vault_document_status_proto_goTypes = []interface{}{
	(*DocumentStatus)(nil),       // 0: vault.doc_status.DocumentStatus
	(*DocumentListResponse)(nil), // 1: vault.doc_status.DocumentListResponse
	(*DocumentSmartReport)(nil),  // 2: vault.doc_status.DocumentSmartReport
	(*DocumentInfo)(nil),         // 3: vault.doc_status.DocumentInfo
	(*DocumentAccessible)(nil),   // 4: vault.doc_status.DocumentAccessible
	(*DocumentListRequest)(nil),  // 5: vault.doc_status.DocumentListRequest
}
var file_vault_document_status_proto_depIdxs = []int32{
	4, // 0: vault.doc_status.DocumentStatus.document_accessible_info:type_name -> vault.doc_status.DocumentAccessible
	3, // 1: vault.doc_status.DocumentStatus.document_info:type_name -> vault.doc_status.DocumentInfo
	0, // 2: vault.doc_status.DocumentListResponse.document_status:type_name -> vault.doc_status.DocumentStatus
	2, // 3: vault.doc_status.DocumentAccessible.document_smart_report:type_name -> vault.doc_status.DocumentSmartReport
	3, // 4: vault.doc_status.DocumentAccessible.document_info:type_name -> vault.doc_status.DocumentInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vault_document_status_proto_init() }
func file_vault_document_status_proto_init() {
	if File_vault_document_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vault_document_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_document_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_document_status_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentSmartReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_document_status_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_document_status_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentAccessible); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_document_status_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vault_document_status_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DocumentStatus_DocumentAccessibleInfo)(nil),
		(*DocumentStatus_DocumentInfo)(nil),
	}
	file_vault_document_status_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_vault_document_status_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vault_document_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vault_document_status_proto_goTypes,
		DependencyIndexes: file_vault_document_status_proto_depIdxs,
		MessageInfos:      file_vault_document_status_proto_msgTypes,
	}.Build()
	File_vault_document_status_proto = out.File
	file_vault_document_status_proto_rawDesc = nil
	file_vault_document_status_proto_goTypes = nil
	file_vault_document_status_proto_depIdxs = nil
}
