// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: insurance/insurance_expired_policies.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Insurance_ExpiredPoliciesResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var expiredPolicies: [Insurance_Policy] = []

  public var nextToken: String {
    get {return _nextToken ?? String()}
    set {_nextToken = newValue}
  }
  /// Returns true if `nextToken` has been explicitly set.
  public var hasNextToken: Bool {return self._nextToken != nil}
  /// Clears the value of `nextToken`. Subsequent reads from it will return its default value.
  public mutating func clearNextToken() {self._nextToken = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _nextToken: String? = nil
}

public struct Insurance_InsuranceExpiredPoliciesAPIResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Insurance_InsuranceExpiredPoliciesAPIResponse.OneOf_Result? = nil

  public var response: Insurance_ExpiredPoliciesResponse {
    get {
      if case .response(let v)? = result {return v}
      return Insurance_ExpiredPoliciesResponse()
    }
    set {result = .response(newValue)}
  }

  public var error: Insurance_InsuranceExpiredPoliciesAPIResponse.Error {
    get {
      if case .error(let v)? = result {return v}
      return Insurance_InsuranceExpiredPoliciesAPIResponse.Error()
    }
    set {result = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Result: Equatable {
    case response(Insurance_ExpiredPoliciesResponse)
    case error(Insurance_InsuranceExpiredPoliciesAPIResponse.Error)

  #if !swift(>=4.1)
    public static func ==(lhs: Insurance_InsuranceExpiredPoliciesAPIResponse.OneOf_Result, rhs: Insurance_InsuranceExpiredPoliciesAPIResponse.OneOf_Result) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.response, .response): return {
        guard case .response(let l) = lhs, case .response(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.error, .error): return {
        guard case .error(let l) = lhs, case .error(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  /// ErrorCode represents list of errors 
  public enum ErrorCode: SwiftProtobuf.Enum {
    public typealias RawValue = Int

    /// Error -> Unspecified.
    case errorUnspecified // = 0
    case UNRECOGNIZED(Int)

    public init() {
      self = .errorUnspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .errorUnspecified
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .errorUnspecified: return 0
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  /// Error represents error resonse of API 
  public struct Error {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Error Code.
    public var code: Insurance_InsuranceExpiredPoliciesAPIResponse.ErrorCode = .errorUnspecified

    /// Error Message.
    public var message: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

#if swift(>=4.2)

extension Insurance_InsuranceExpiredPoliciesAPIResponse.ErrorCode: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Insurance_InsuranceExpiredPoliciesAPIResponse.ErrorCode] = [
    .errorUnspecified,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Insurance_ExpiredPoliciesResponse: @unchecked Sendable {}
extension Insurance_InsuranceExpiredPoliciesAPIResponse: @unchecked Sendable {}
extension Insurance_InsuranceExpiredPoliciesAPIResponse.OneOf_Result: @unchecked Sendable {}
extension Insurance_InsuranceExpiredPoliciesAPIResponse.ErrorCode: @unchecked Sendable {}
extension Insurance_InsuranceExpiredPoliciesAPIResponse.Error: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "insurance"

extension Insurance_ExpiredPoliciesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ExpiredPoliciesResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "expired_policies"),
    2: .standard(proto: "next_token"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.expiredPolicies) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._nextToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.expiredPolicies.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.expiredPolicies, fieldNumber: 1)
    }
    try { if let v = self._nextToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_ExpiredPoliciesResponse, rhs: Insurance_ExpiredPoliciesResponse) -> Bool {
    if lhs.expiredPolicies != rhs.expiredPolicies {return false}
    if lhs._nextToken != rhs._nextToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_InsuranceExpiredPoliciesAPIResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InsuranceExpiredPoliciesAPIResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "response"),
    2: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Insurance_ExpiredPoliciesResponse?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .response(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .response(v)
        }
      }()
      case 2: try {
        var v: Insurance_InsuranceExpiredPoliciesAPIResponse.Error?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .error(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .response?: try {
      guard case .response(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_InsuranceExpiredPoliciesAPIResponse, rhs: Insurance_InsuranceExpiredPoliciesAPIResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Insurance_InsuranceExpiredPoliciesAPIResponse.ErrorCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ERROR_UNSPECIFIED"),
  ]
}

extension Insurance_InsuranceExpiredPoliciesAPIResponse.Error: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Insurance_InsuranceExpiredPoliciesAPIResponse.protoMessageName + ".Error"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
    2: .same(proto: "message"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .errorUnspecified {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Insurance_InsuranceExpiredPoliciesAPIResponse.Error, rhs: Insurance_InsuranceExpiredPoliciesAPIResponse.Error) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
