// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.28.2
// source: vault/bannersv4.proto

package bannersv4

import (
	bannerbodyparameter "github.com/eka-care/proto-contracts/go/vault/bannerbodyparameter"
	cta "github.com/eka-care/proto-contracts/go/vault/cta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner_Item_Highlight int32

const (
	Banner_Item_TYPE_UNSPECIFIED Banner_Item_Highlight = 0 // Unspecified.
	Banner_Item_TYPE_ONE         Banner_Item_Highlight = 1
	Banner_Item_TYPE_TWO         Banner_Item_Highlight = 2
	Banner_Item_TYPE_THREE       Banner_Item_Highlight = 3
	Banner_Item_TYPE_FOUR        Banner_Item_Highlight = 4
)

// Enum value maps for Banner_Item_Highlight.
var (
	Banner_Item_Highlight_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ONE",
		2: "TYPE_TWO",
		3: "TYPE_THREE",
		4: "TYPE_FOUR",
	}
	Banner_Item_Highlight_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_ONE":         1,
		"TYPE_TWO":         2,
		"TYPE_THREE":       3,
		"TYPE_FOUR":        4,
	}
)

func (x Banner_Item_Highlight) Enum() *Banner_Item_Highlight {
	p := new(Banner_Item_Highlight)
	*p = x
	return p
}

func (x Banner_Item_Highlight) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Banner_Item_Highlight) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_bannersv4_proto_enumTypes[0].Descriptor()
}

func (Banner_Item_Highlight) Type() protoreflect.EnumType {
	return &file_vault_bannersv4_proto_enumTypes[0]
}

func (x Banner_Item_Highlight) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Banner_Item_Highlight.Descriptor instead.
func (Banner_Item_Highlight) EnumDescriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{0, 0, 0}
}

// ErrorCode represents list of errors
type BannersAPIResponse_ErrorCode int32

const (
	BannersAPIResponse_ERROR_UNSPECIFIED BannersAPIResponse_ErrorCode = 0 // Error -> Unspecified.
)

// Enum value maps for BannersAPIResponse_ErrorCode.
var (
	BannersAPIResponse_ErrorCode_name = map[int32]string{
		0: "ERROR_UNSPECIFIED",
	}
	BannersAPIResponse_ErrorCode_value = map[string]int32{
		"ERROR_UNSPECIFIED": 0,
	}
)

func (x BannersAPIResponse_ErrorCode) Enum() *BannersAPIResponse_ErrorCode {
	p := new(BannersAPIResponse_ErrorCode)
	*p = x
	return p
}

func (x BannersAPIResponse_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BannersAPIResponse_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_bannersv4_proto_enumTypes[1].Descriptor()
}

func (BannersAPIResponse_ErrorCode) Type() protoreflect.EnumType {
	return &file_vault_bannersv4_proto_enumTypes[1]
}

func (x BannersAPIResponse_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BannersAPIResponse_ErrorCode.Descriptor instead.
func (BannersAPIResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{2, 0}
}

// Banner represents banner info.
type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Banner_Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Hash string       `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // Hash of the banner.
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_bannersv4_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_vault_bannersv4_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetItem() *Banner_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Banner) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// BannersResponse represents banners on records page such as gmail sync,
// insights etc.
type BannersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banners       []*Banner `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
	NextPageToken *string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
}

func (x *BannersResponse) Reset() {
	*x = BannersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_bannersv4_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannersResponse) ProtoMessage() {}

func (x *BannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_bannersv4_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannersResponse.ProtoReflect.Descriptor instead.
func (*BannersResponse) Descriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{1}
}

func (x *BannersResponse) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

func (x *BannersResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type BannersAPIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*BannersAPIResponse_Response
	//	*BannersAPIResponse_Error_
	Result isBannersAPIResponse_Result `protobuf_oneof:"result"`
}

func (x *BannersAPIResponse) Reset() {
	*x = BannersAPIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_bannersv4_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannersAPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannersAPIResponse) ProtoMessage() {}

func (x *BannersAPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_bannersv4_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannersAPIResponse.ProtoReflect.Descriptor instead.
func (*BannersAPIResponse) Descriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{2}
}

func (m *BannersAPIResponse) GetResult() isBannersAPIResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *BannersAPIResponse) GetResponse() *BannersResponse {
	if x, ok := x.GetResult().(*BannersAPIResponse_Response); ok {
		return x.Response
	}
	return nil
}

func (x *BannersAPIResponse) GetError() *BannersAPIResponse_Error {
	if x, ok := x.GetResult().(*BannersAPIResponse_Error_); ok {
		return x.Error
	}
	return nil
}

type isBannersAPIResponse_Result interface {
	isBannersAPIResponse_Result()
}

type BannersAPIResponse_Response struct {
	Response *BannersResponse `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type BannersAPIResponse_Error_ struct {
	Error *BannersAPIResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*BannersAPIResponse_Response) isBannersAPIResponse_Result() {}

func (*BannersAPIResponse_Error_) isBannersAPIResponse_Result() {}

type Banner_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title          string                                    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                                                                                                      // Title of the banner.
	SubTitle       *string                                   `protobuf:"bytes,2,opt,name=sub_title,json=subTitle,proto3,oneof" json:"sub_title,omitempty"`                                                                          // Sub Title of the banner.
	Cta            *cta.CTA                                  `protobuf:"bytes,3,opt,name=cta,proto3" json:"cta,omitempty"`                                                                                                          // CTA configuration for button.
	BannerId       string                                    `protobuf:"bytes,4,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`                                                                                // ID represents banner identifier for tracking in Mixpanel.
	BodyParameters []bannerbodyparameter.BannerBodyParameter `protobuf:"varint,5,rep,packed,name=body_parameters,json=bodyParameters,proto3,enum=vault.banner_body_parameter.BannerBodyParameter" json:"body_parameters,omitempty"` // dynamic parameters with-in sub title to be filled by client.
	Assets         *Banner_Item_Assets                       `protobuf:"bytes,6,opt,name=assets,proto3" json:"assets,omitempty"`                                                                                                    // Assets for the banner.
	Highlight      *Banner_Item_Highlight                    `protobuf:"varint,7,opt,name=highlight,proto3,enum=vault.bannersv4.Banner_Item_Highlight,oneof" json:"highlight,omitempty"`                                            // Hightlight type of the banner.
}

func (x *Banner_Item) Reset() {
	*x = Banner_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_bannersv4_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner_Item) ProtoMessage() {}

func (x *Banner_Item) ProtoReflect() protoreflect.Message {
	mi := &file_vault_bannersv4_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner_Item.ProtoReflect.Descriptor instead.
func (*Banner_Item) Descriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Banner_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner_Item) GetSubTitle() string {
	if x != nil && x.SubTitle != nil {
		return *x.SubTitle
	}
	return ""
}

func (x *Banner_Item) GetCta() *cta.CTA {
	if x != nil {
		return x.Cta
	}
	return nil
}

func (x *Banner_Item) GetBannerId() string {
	if x != nil {
		return x.BannerId
	}
	return ""
}

func (x *Banner_Item) GetBodyParameters() []bannerbodyparameter.BannerBodyParameter {
	if x != nil {
		return x.BodyParameters
	}
	return nil
}

func (x *Banner_Item) GetAssets() *Banner_Item_Assets {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *Banner_Item) GetHighlight() Banner_Item_Highlight {
	if x != nil && x.Highlight != nil {
		return *x.Highlight
	}
	return Banner_Item_TYPE_UNSPECIFIED
}

type Banner_Item_Assets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BgAsset  *Banner_Item_Assets_Img `protobuf:"bytes,1,opt,name=bg_asset,json=bgAsset,proto3" json:"bg_asset,omitempty"`
	TopAsset *Banner_Item_Assets_Img `protobuf:"bytes,2,opt,name=top_asset,json=topAsset,proto3,oneof" json:"top_asset,omitempty"`
}

func (x *Banner_Item_Assets) Reset() {
	*x = Banner_Item_Assets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_bannersv4_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner_Item_Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner_Item_Assets) ProtoMessage() {}

func (x *Banner_Item_Assets) ProtoReflect() protoreflect.Message {
	mi := &file_vault_bannersv4_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner_Item_Assets.ProtoReflect.Descriptor instead.
func (*Banner_Item_Assets) Descriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Banner_Item_Assets) GetBgAsset() *Banner_Item_Assets_Img {
	if x != nil {
		return x.BgAsset
	}
	return nil
}

func (x *Banner_Item_Assets) GetTopAsset() *Banner_Item_Assets_Img {
	if x != nil {
		return x.TopAsset
	}
	return nil
}

type Banner_Item_Assets_Img struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Image:
	//
	//	*Banner_Item_Assets_Img_Img
	//	*Banner_Item_Assets_Img_Lottie
	Image isBanner_Item_Assets_Img_Image `protobuf_oneof:"image"`
}

func (x *Banner_Item_Assets_Img) Reset() {
	*x = Banner_Item_Assets_Img{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_bannersv4_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner_Item_Assets_Img) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner_Item_Assets_Img) ProtoMessage() {}

func (x *Banner_Item_Assets_Img) ProtoReflect() protoreflect.Message {
	mi := &file_vault_bannersv4_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner_Item_Assets_Img.ProtoReflect.Descriptor instead.
func (*Banner_Item_Assets_Img) Descriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (m *Banner_Item_Assets_Img) GetImage() isBanner_Item_Assets_Img_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (x *Banner_Item_Assets_Img) GetImg() string {
	if x, ok := x.GetImage().(*Banner_Item_Assets_Img_Img); ok {
		return x.Img
	}
	return ""
}

func (x *Banner_Item_Assets_Img) GetLottie() string {
	if x, ok := x.GetImage().(*Banner_Item_Assets_Img_Lottie); ok {
		return x.Lottie
	}
	return ""
}

type isBanner_Item_Assets_Img_Image interface {
	isBanner_Item_Assets_Img_Image()
}

type Banner_Item_Assets_Img_Img struct {
	Img string `protobuf:"bytes,1,opt,name=img,proto3,oneof"` // Image link for the banner.
}

type Banner_Item_Assets_Img_Lottie struct {
	Lottie string `protobuf:"bytes,2,opt,name=lottie,proto3,oneof"` // Lottie link for the banner.
}

func (*Banner_Item_Assets_Img_Img) isBanner_Item_Assets_Img_Image() {}

func (*Banner_Item_Assets_Img_Lottie) isBanner_Item_Assets_Img_Image() {}

// Error represents error resonse of API
type BannersAPIResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    BannersAPIResponse_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=vault.bannersv4.BannersAPIResponse_ErrorCode" json:"code,omitempty"` // Error Code.
	Message string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                              // Error Message.
}

func (x *BannersAPIResponse_Error) Reset() {
	*x = BannersAPIResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_bannersv4_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannersAPIResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannersAPIResponse_Error) ProtoMessage() {}

func (x *BannersAPIResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_vault_bannersv4_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannersAPIResponse_Error.ProtoReflect.Descriptor instead.
func (*BannersAPIResponse_Error) Descriptor() ([]byte, []int) {
	return file_vault_bannersv4_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BannersAPIResponse_Error) GetCode() BannersAPIResponse_ErrorCode {
	if x != nil {
		return x.Code
	}
	return BannersAPIResponse_ERROR_UNSPECIFIED
}

func (x *BannersAPIResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vault_bannersv4_proto protoreflect.FileDescriptor

var file_vault_bannersv4_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76,
	0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x1a, 0x0f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f,
	0x63, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x06, 0x0a,
	0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x1a, 0xc3, 0x05,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x09,
	0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23,
	0x0a, 0x03, 0x63, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x54, 0x41, 0x52, 0x03,
	0x63, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x59, 0x0a, 0x0f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x6f,
	0x64, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0e, 0x62, 0x6f, 0x64,
	0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x3b, 0x0a, 0x06, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x2e, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x49, 0x0a, 0x09, 0x68, 0x69, 0x67, 0x68,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x2e, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x48, 0x69, 0x67, 0x68, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x48, 0x01, 0x52, 0x09, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x88, 0x01, 0x01, 0x1a, 0xe3, 0x01, 0x0a, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x42,
	0x0a, 0x08, 0x62, 0x67, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73,
	0x76, 0x34, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x49, 0x6d, 0x67, 0x52, 0x07, 0x62, 0x67, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x12, 0x49, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x49, 0x6d, 0x67, 0x48, 0x00,
	0x52, 0x08, 0x74, 0x6f, 0x70, 0x41, 0x73, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x1a, 0x3c, 0x0a,
	0x03, 0x49, 0x6d, 0x67, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12, 0x18, 0x0a, 0x06, 0x6c, 0x6f, 0x74, 0x74,
	0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x74, 0x74,
	0x69, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x74, 0x6f, 0x70, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x22, 0x5c, 0x0a, 0x09, 0x48, 0x69, 0x67,
	0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x54, 0x57, 0x4f, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x54, 0x48, 0x52, 0x45, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x46, 0x4f, 0x55, 0x52, 0x10, 0x04, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x75, 0x62, 0x5f,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0f, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x0f, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6e, 0x65, 0x78, 0x74,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xab, 0x02, 0x0a, 0x12,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x73, 0x76, 0x34, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x41, 0x50, 0x49, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x64, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x41,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x76,
	0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x76, 0x34, 0x2e, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x42,
	0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x61, 0x2d, 0x63, 0x61, 0x72, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x73, 0x76, 0x34, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vault_bannersv4_proto_rawDescOnce sync.Once
	file_vault_bannersv4_proto_rawDescData = file_vault_bannersv4_proto_rawDesc
)

func file_vault_bannersv4_proto_rawDescGZIP() []byte {
	file_vault_bannersv4_proto_rawDescOnce.Do(func() {
		file_vault_bannersv4_proto_rawDescData = protoimpl.X.CompressGZIP(file_vault_bannersv4_proto_rawDescData)
	})
	return file_vault_bannersv4_proto_rawDescData
}

var file_vault_bannersv4_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vault_bannersv4_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vault_bannersv4_proto_goTypes = []interface{}{
	(Banner_Item_Highlight)(0),                   // 0: vault.bannersv4.Banner.Item.Highlight
	(BannersAPIResponse_ErrorCode)(0),            // 1: vault.bannersv4.BannersAPIResponse.ErrorCode
	(*Banner)(nil),                               // 2: vault.bannersv4.Banner
	(*BannersResponse)(nil),                      // 3: vault.bannersv4.BannersResponse
	(*BannersAPIResponse)(nil),                   // 4: vault.bannersv4.BannersAPIResponse
	(*Banner_Item)(nil),                          // 5: vault.bannersv4.Banner.Item
	(*Banner_Item_Assets)(nil),                   // 6: vault.bannersv4.Banner.Item.Assets
	(*Banner_Item_Assets_Img)(nil),               // 7: vault.bannersv4.Banner.Item.Assets.Img
	(*BannersAPIResponse_Error)(nil),             // 8: vault.bannersv4.BannersAPIResponse.Error
	(*cta.CTA)(nil),                              // 9: vault.common.CTA
	(bannerbodyparameter.BannerBodyParameter)(0), // 10: vault.banner_body_parameter.BannerBodyParameter
}
var file_vault_bannersv4_proto_depIdxs = []int32{
	5,  // 0: vault.bannersv4.Banner.item:type_name -> vault.bannersv4.Banner.Item
	2,  // 1: vault.bannersv4.BannersResponse.banners:type_name -> vault.bannersv4.Banner
	3,  // 2: vault.bannersv4.BannersAPIResponse.response:type_name -> vault.bannersv4.BannersResponse
	8,  // 3: vault.bannersv4.BannersAPIResponse.error:type_name -> vault.bannersv4.BannersAPIResponse.Error
	9,  // 4: vault.bannersv4.Banner.Item.cta:type_name -> vault.common.CTA
	10, // 5: vault.bannersv4.Banner.Item.body_parameters:type_name -> vault.banner_body_parameter.BannerBodyParameter
	6,  // 6: vault.bannersv4.Banner.Item.assets:type_name -> vault.bannersv4.Banner.Item.Assets
	0,  // 7: vault.bannersv4.Banner.Item.highlight:type_name -> vault.bannersv4.Banner.Item.Highlight
	7,  // 8: vault.bannersv4.Banner.Item.Assets.bg_asset:type_name -> vault.bannersv4.Banner.Item.Assets.Img
	7,  // 9: vault.bannersv4.Banner.Item.Assets.top_asset:type_name -> vault.bannersv4.Banner.Item.Assets.Img
	1,  // 10: vault.bannersv4.BannersAPIResponse.Error.code:type_name -> vault.bannersv4.BannersAPIResponse.ErrorCode
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_vault_bannersv4_proto_init() }
func file_vault_bannersv4_proto_init() {
	if File_vault_bannersv4_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vault_bannersv4_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_bannersv4_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_bannersv4_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannersAPIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_bannersv4_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_bannersv4_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner_Item_Assets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_bannersv4_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner_Item_Assets_Img); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_bannersv4_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannersAPIResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vault_bannersv4_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_vault_bannersv4_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*BannersAPIResponse_Response)(nil),
		(*BannersAPIResponse_Error_)(nil),
	}
	file_vault_bannersv4_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_vault_bannersv4_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_vault_bannersv4_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Banner_Item_Assets_Img_Img)(nil),
		(*Banner_Item_Assets_Img_Lottie)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vault_bannersv4_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vault_bannersv4_proto_goTypes,
		DependencyIndexes: file_vault_bannersv4_proto_depIdxs,
		EnumInfos:         file_vault_bannersv4_proto_enumTypes,
		MessageInfos:      file_vault_bannersv4_proto_msgTypes,
	}.Build()
	File_vault_bannersv4_proto = out.File
	file_vault_bannersv4_proto_rawDesc = nil
	file_vault_bannersv4_proto_goTypes = nil
	file_vault_bannersv4_proto_depIdxs = nil
}
