// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: vault/banners.proto

package banners

import (
	bannerbodyparameter "github.com/eka-care/proto-contracts/go/vault/bannerbodyparameter"
	cta "github.com/eka-care/proto-contracts/go/vault/cta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BannersResponse represents banners on records page such as gmail sync, insights etc.
type BannersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Banner represents multiple banner on the records screen.
	Banners []*Banner `protobuf:"bytes,1,rep,name=banners,proto3" json:"banners,omitempty"`
}

func (x *BannersResponse) Reset() {
	*x = BannersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_banners_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannersResponse) ProtoMessage() {}

func (x *BannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_banners_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannersResponse.ProtoReflect.Descriptor instead.
func (*BannersResponse) Descriptor() ([]byte, []int) {
	return file_vault_banners_proto_rawDescGZIP(), []int{0}
}

func (x *BannersResponse) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

// Banner represents configuration.
type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`     // Title of the banner.
	Body   *string  `protobuf:"bytes,2,opt,name=body,proto3,oneof" json:"body,omitempty"` // Body or description of the banner.
	Cta    *cta.CTA `protobuf:"bytes,3,opt,name=cta,proto3" json:"cta,omitempty"`         // CTA configuration for button.
	Colour string   `protobuf:"bytes,4,opt,name=colour,proto3" json:"colour,omitempty"`   // Colour of the banner in hex code.
	// Types that are assignable to Image:
	//
	//	*Banner_Img
	//	*Banner_Lottie
	Image          isBanner_Image                            `protobuf_oneof:"image"`
	BodyParameters []bannerbodyparameter.BannerBodyParameter `protobuf:"varint,7,rep,packed,name=body_parameters,json=bodyParameters,proto3,enum=vault.banner_body_parameter.BannerBodyParameter" json:"body_parameters,omitempty"` // dynamic parameters with body.
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_banners_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_vault_banners_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_vault_banners_proto_rawDescGZIP(), []int{1}
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

func (x *Banner) GetCta() *cta.CTA {
	if x != nil {
		return x.Cta
	}
	return nil
}

func (x *Banner) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

func (m *Banner) GetImage() isBanner_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (x *Banner) GetImg() string {
	if x, ok := x.GetImage().(*Banner_Img); ok {
		return x.Img
	}
	return ""
}

func (x *Banner) GetLottie() string {
	if x, ok := x.GetImage().(*Banner_Lottie); ok {
		return x.Lottie
	}
	return ""
}

func (x *Banner) GetBodyParameters() []bannerbodyparameter.BannerBodyParameter {
	if x != nil {
		return x.BodyParameters
	}
	return nil
}

type isBanner_Image interface {
	isBanner_Image()
}

type Banner_Img struct {
	Img string `protobuf:"bytes,5,opt,name=img,proto3,oneof"` // Image link for the banner.
}

type Banner_Lottie struct {
	Lottie string `protobuf:"bytes,6,opt,name=lottie,proto3,oneof"` // Lottie link for the banner.
}

func (*Banner_Img) isBanner_Image() {}

func (*Banner_Lottie) isBanner_Image() {}

var File_vault_banners_proto protoreflect.FileDescriptor

var file_vault_banners_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x73, 0x1a, 0x0f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x63, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0f, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76,
	0x61, 0x75, 0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x8f, 0x02, 0x0a,
	0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x17, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x03, 0x63, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x43, 0x54, 0x41, 0x52, 0x03, 0x63, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c,
	0x6f, 0x75, 0x72, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12, 0x18, 0x0a, 0x06, 0x6c, 0x6f, 0x74, 0x74, 0x69,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x74, 0x74, 0x69,
	0x65, 0x12, 0x59, 0x0a, 0x0f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42,
	0x6f, 0x64, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0e, 0x62, 0x6f,
	0x64, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x42, 0x07, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x36,
	0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x61,
	0x2d, 0x63, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vault_banners_proto_rawDescOnce sync.Once
	file_vault_banners_proto_rawDescData = file_vault_banners_proto_rawDesc
)

func file_vault_banners_proto_rawDescGZIP() []byte {
	file_vault_banners_proto_rawDescOnce.Do(func() {
		file_vault_banners_proto_rawDescData = protoimpl.X.CompressGZIP(file_vault_banners_proto_rawDescData)
	})
	return file_vault_banners_proto_rawDescData
}

var file_vault_banners_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vault_banners_proto_goTypes = []interface{}{
	(*BannersResponse)(nil), // 0: vault.banners.BannersResponse
	(*Banner)(nil),          // 1: vault.banners.Banner
	(*cta.CTA)(nil),         // 2: vault.common.CTA
	(bannerbodyparameter.BannerBodyParameter)(0), // 3: vault.banner_body_parameter.BannerBodyParameter
}
var file_vault_banners_proto_depIdxs = []int32{
	1, // 0: vault.banners.BannersResponse.banners:type_name -> vault.banners.Banner
	2, // 1: vault.banners.Banner.cta:type_name -> vault.common.CTA
	3, // 2: vault.banners.Banner.body_parameters:type_name -> vault.banner_body_parameter.BannerBodyParameter
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vault_banners_proto_init() }
func file_vault_banners_proto_init() {
	if File_vault_banners_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vault_banners_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_banners_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vault_banners_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Banner_Img)(nil),
		(*Banner_Lottie)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vault_banners_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vault_banners_proto_goTypes,
		DependencyIndexes: file_vault_banners_proto_depIdxs,
		MessageInfos:      file_vault_banners_proto_msgTypes,
	}.Build()
	File_vault_banners_proto = out.File
	file_vault_banners_proto_rawDesc = nil
	file_vault_banners_proto_goTypes = nil
	file_vault_banners_proto_depIdxs = nil
}
