// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: gmail/sync_type.proto

package gmailsync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncType int32

const (
	SyncType_TYPE_UNSPECIFIED SyncType = 0 // Unspecified.
	SyncType_TYPE_PERIODIC    SyncType = 1 // PERIODIC.
	SyncType_TYPE_RERUN       SyncType = 2 // RERUN.
	SyncType_TYPE_INITIAL     SyncType = 3 // INITIAL.
	SyncType_TYPE_ONDEMAND    SyncType = 4 // ONDEMAND.
)

// Enum value maps for SyncType.
var (
	SyncType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PERIODIC",
		2: "TYPE_RERUN",
		3: "TYPE_INITIAL",
		4: "TYPE_ONDEMAND",
	}
	SyncType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PERIODIC":    1,
		"TYPE_RERUN":       2,
		"TYPE_INITIAL":     3,
		"TYPE_ONDEMAND":    4,
	}
)

func (x SyncType) Enum() *SyncType {
	p := new(SyncType)
	*p = x
	return p
}

func (x SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_gmail_sync_type_proto_enumTypes[0].Descriptor()
}

func (SyncType) Type() protoreflect.EnumType {
	return &file_gmail_sync_type_proto_enumTypes[0]
}

func (x SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncType.Descriptor instead.
func (SyncType) EnumDescriptor() ([]byte, []int) {
	return file_gmail_sync_type_proto_rawDescGZIP(), []int{0}
}

var File_gmail_sync_type_proto protoreflect.FileDescriptor

var file_gmail_sync_type_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x79,
	0x6e, 0x63, 0x2a, 0x68, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x45, 0x52,
	0x49, 0x4f, 0x44, 0x49, 0x43, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x45, 0x52, 0x55, 0x4e, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4f, 0x4e, 0x44, 0x45, 0x4d, 0x41, 0x4e, 0x44, 0x10, 0x04, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x61, 0x2d, 0x63,
	0x61, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x79, 0x6e, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gmail_sync_type_proto_rawDescOnce sync.Once
	file_gmail_sync_type_proto_rawDescData = file_gmail_sync_type_proto_rawDesc
)

func file_gmail_sync_type_proto_rawDescGZIP() []byte {
	file_gmail_sync_type_proto_rawDescOnce.Do(func() {
		file_gmail_sync_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_gmail_sync_type_proto_rawDescData)
	})
	return file_gmail_sync_type_proto_rawDescData
}

var file_gmail_sync_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gmail_sync_type_proto_goTypes = []interface{}{
	(SyncType)(0), // 0: gmailsync.SyncType
}
var file_gmail_sync_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gmail_sync_type_proto_init() }
func file_gmail_sync_type_proto_init() {
	if File_gmail_sync_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gmail_sync_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gmail_sync_type_proto_goTypes,
		DependencyIndexes: file_gmail_sync_type_proto_depIdxs,
		EnumInfos:         file_gmail_sync_type_proto_enumTypes,
	}.Build()
	File_gmail_sync_type_proto = out.File
	file_gmail_sync_type_proto_rawDesc = nil
	file_gmail_sync_type_proto_goTypes = nil
	file_gmail_sync_type_proto_depIdxs = nil
}
