// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vault/banners.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// BannersResponse represents banners on records page such as gmail sync,
/// insights etc. 
public struct Vault_Banners_BannersResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Banner represents multiple banner on the records screen. 
  public var banners: [Vault_Banners_Banner] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Banner represents configuration. 
public struct Vault_Banners_Banner {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Title of the banner.
  public var title: String = String()

  /// Body or description of the banner.
  public var body: String {
    get {return _body ?? String()}
    set {_body = newValue}
  }
  /// Returns true if `body` has been explicitly set.
  public var hasBody: Bool {return self._body != nil}
  /// Clears the value of `body`. Subsequent reads from it will return its default value.
  public mutating func clearBody() {self._body = nil}

  /// CTA configuration for button.
  public var cta: Vault_Common_CTA {
    get {return _cta ?? Vault_Common_CTA()}
    set {_cta = newValue}
  }
  /// Returns true if `cta` has been explicitly set.
  public var hasCta: Bool {return self._cta != nil}
  /// Clears the value of `cta`. Subsequent reads from it will return its default value.
  public mutating func clearCta() {self._cta = nil}

  /// Colour of the banner in hex code.
  public var colour: String = String()

  /// Colour of the banner in hex code.
  public var iconBackgroundColor: String = String()

  /// Colour of the tag background in hex code.
  public var tagBackgroundColor: String = String()

  /// Colour of the tag title in hex code.
  public var titleBackgroundColo: String = String()

  public var image: Vault_Banners_Banner.OneOf_Image? = nil

  /// Image link for the banner.
  public var img: String {
    get {
      if case .img(let v)? = image {return v}
      return String()
    }
    set {image = .img(newValue)}
  }

  /// Lottie link for the banner.
  public var lottie: String {
    get {
      if case .lottie(let v)? = image {return v}
      return String()
    }
    set {image = .lottie(newValue)}
  }

  /// dynamic parameters with body.
  public var bodyParameters: [Vault_BannerBodyParameter_BannerBodyParameter] = []

  /// ID represents banner/card identifier.
  public var bannerID: String {
    get {return _bannerID ?? String()}
    set {_bannerID = newValue}
  }
  /// Returns true if `bannerID` has been explicitly set.
  public var hasBannerID: Bool {return self._bannerID != nil}
  /// Clears the value of `bannerID`. Subsequent reads from it will return its default value.
  public mutating func clearBannerID() {self._bannerID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Image: Equatable {
    /// Image link for the banner.
    case img(String)
    /// Lottie link for the banner.
    case lottie(String)

  #if !swift(>=4.1)
    public static func ==(lhs: Vault_Banners_Banner.OneOf_Image, rhs: Vault_Banners_Banner.OneOf_Image) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.img, .img): return {
        guard case .img(let l) = lhs, case .img(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.lottie, .lottie): return {
        guard case .lottie(let l) = lhs, case .lottie(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}

  fileprivate var _body: String? = nil
  fileprivate var _cta: Vault_Common_CTA? = nil
  fileprivate var _bannerID: String? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Vault_Banners_BannersResponse: @unchecked Sendable {}
extension Vault_Banners_Banner: @unchecked Sendable {}
extension Vault_Banners_Banner.OneOf_Image: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vault.banners"

extension Vault_Banners_BannersResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BannersResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "banners"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.banners) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.banners.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.banners, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_Banners_BannersResponse, rhs: Vault_Banners_BannersResponse) -> Bool {
    if lhs.banners != rhs.banners {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Vault_Banners_Banner: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Banner"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "title"),
    2: .same(proto: "body"),
    3: .same(proto: "cta"),
    4: .same(proto: "colour"),
    5: .same(proto: "iconBackgroundColor"),
    6: .same(proto: "tagBackgroundColor"),
    7: .same(proto: "titleBackgroundColo"),
    8: .same(proto: "img"),
    9: .same(proto: "lottie"),
    10: .standard(proto: "body_parameters"),
    11: .standard(proto: "banner_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._body) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._cta) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.colour) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.iconBackgroundColor) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.tagBackgroundColor) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.titleBackgroundColo) }()
      case 8: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.image != nil {try decoder.handleConflictingOneOf()}
          self.image = .img(v)
        }
      }()
      case 9: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.image != nil {try decoder.handleConflictingOneOf()}
          self.image = .lottie(v)
        }
      }()
      case 10: try { try decoder.decodeRepeatedEnumField(value: &self.bodyParameters) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self._bannerID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 1)
    }
    try { if let v = self._body {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._cta {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.colour.isEmpty {
      try visitor.visitSingularStringField(value: self.colour, fieldNumber: 4)
    }
    if !self.iconBackgroundColor.isEmpty {
      try visitor.visitSingularStringField(value: self.iconBackgroundColor, fieldNumber: 5)
    }
    if !self.tagBackgroundColor.isEmpty {
      try visitor.visitSingularStringField(value: self.tagBackgroundColor, fieldNumber: 6)
    }
    if !self.titleBackgroundColo.isEmpty {
      try visitor.visitSingularStringField(value: self.titleBackgroundColo, fieldNumber: 7)
    }
    switch self.image {
    case .img?: try {
      guard case .img(let v)? = self.image else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    }()
    case .lottie?: try {
      guard case .lottie(let v)? = self.image else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    }()
    case nil: break
    }
    if !self.bodyParameters.isEmpty {
      try visitor.visitPackedEnumField(value: self.bodyParameters, fieldNumber: 10)
    }
    try { if let v = self._bannerID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_Banners_Banner, rhs: Vault_Banners_Banner) -> Bool {
    if lhs.title != rhs.title {return false}
    if lhs._body != rhs._body {return false}
    if lhs._cta != rhs._cta {return false}
    if lhs.colour != rhs.colour {return false}
    if lhs.iconBackgroundColor != rhs.iconBackgroundColor {return false}
    if lhs.tagBackgroundColor != rhs.tagBackgroundColor {return false}
    if lhs.titleBackgroundColo != rhs.titleBackgroundColo {return false}
    if lhs.image != rhs.image {return false}
    if lhs.bodyParameters != rhs.bodyParameters {return false}
    if lhs._bannerID != rhs._bannerID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
