// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vault/document_status.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// DocumentStatus represents status of given document id list. 
public struct Vault_DocStatus_DocumentStatus {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var documentStatusResponse: Vault_DocStatus_DocumentStatus.OneOf_DocumentStatusResponse? = nil

  /// Not_accessible represents that document is not uploaded to the server.
  public var notAccessible: Vault_DocStatus_NotAccessible {
    get {
      if case .notAccessible(let v)? = documentStatusResponse {return v}
      return Vault_DocStatus_NotAccessible()
    }
    set {documentStatusResponse = .notAccessible(newValue)}
  }

  /// Document_analysis represent document
  public var documentAnalysis: Vault_DocStatus_DocumentAnalysis {
    get {
      if case .documentAnalysis(let v)? = documentStatusResponse {return v}
      return Vault_DocStatus_DocumentAnalysis()
    }
    set {documentStatusResponse = .documentAnalysis(newValue)}
  }

  /// status during processing.
  public var documentInfo: Vault_DocStatus_DocumentInfo {
    get {
      if case .documentInfo(let v)? = documentStatusResponse {return v}
      return Vault_DocStatus_DocumentInfo()
    }
    set {documentStatusResponse = .documentInfo(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_DocumentStatusResponse: Equatable {
    /// Not_accessible represents that document is not uploaded to the server.
    case notAccessible(Vault_DocStatus_NotAccessible)
    /// Document_analysis represent document
    case documentAnalysis(Vault_DocStatus_DocumentAnalysis)
    /// status during processing.
    case documentInfo(Vault_DocStatus_DocumentInfo)

  #if !swift(>=4.1)
    public static func ==(lhs: Vault_DocStatus_DocumentStatus.OneOf_DocumentStatusResponse, rhs: Vault_DocStatus_DocumentStatus.OneOf_DocumentStatusResponse) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.notAccessible, .notAccessible): return {
        guard case .notAccessible(let l) = lhs, case .notAccessible(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.documentAnalysis, .documentAnalysis): return {
        guard case .documentAnalysis(let l) = lhs, case .documentAnalysis(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.documentInfo, .documentInfo): return {
        guard case .documentInfo(let l) = lhs, case .documentInfo(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}
}

/// NotAccessible represents document is not accessible, i.e., not uploaded to the server. 
public struct Vault_DocStatus_NotAccessible {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// DocumentListResponse represents response for the list of documents in processing. 
public struct Vault_DocStatus_DocumentListResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Status of requested document ids.
  public var documentStatus: [Vault_DocStatus_DocumentStatus] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// DocumentSmartReport represents smart report related information. 
public struct Vault_DocStatus_DocumentSmartReport {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Represents if document is a smart report.
  public var isSmartReportAvailable: Bool {
    get {return _isSmartReportAvailable ?? false}
    set {_isSmartReportAvailable = newValue}
  }
  /// Returns true if `isSmartReportAvailable` has been explicitly set.
  public var hasIsSmartReportAvailable: Bool {return self._isSmartReportAvailable != nil}
  /// Clears the value of `isSmartReportAvailable`. Subsequent reads from it will return its default value.
  public mutating func clearIsSmartReportAvailable() {self._isSmartReportAvailable = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _isSmartReportAvailable: Bool? = nil
}

/// DocumentInfo represents document related other info. 
public struct Vault_DocStatus_DocumentInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Thumbnail of the document.
  public var thumbnail: String {
    get {return _thumbnail ?? String()}
    set {_thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  public var hasThumbnail: Bool {return self._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  public mutating func clearThumbnail() {self._thumbnail = nil}

  /// OID of the patient on document.
  public var patientID: String {
    get {return _patientID ?? String()}
    set {_patientID = newValue}
  }
  /// Returns true if `patientID` has been explicitly set.
  public var hasPatientID: Bool {return self._patientID != nil}
  /// Clears the value of `patientID`. Subsequent reads from it will return its default value.
  public mutating func clearPatientID() {self._patientID = nil}

  /// Derived tags of the document.
  public var tags: [String] = []

  /// Date of the document.
  public var documentDate: String {
    get {return _documentDate ?? String()}
    set {_documentDate = newValue}
  }
  /// Returns true if `documentDate` has been explicitly set.
  public var hasDocumentDate: Bool {return self._documentDate != nil}
  /// Clears the value of `documentDate`. Subsequent reads from it will return its default value.
  public mutating func clearDocumentDate() {self._documentDate = nil}

  /// Confirm the scanned data message.
  public var postAnalyzerObservations: String {
    get {return _postAnalyzerObservations ?? String()}
    set {_postAnalyzerObservations = newValue}
  }
  /// Returns true if `postAnalyzerObservations` has been explicitly set.
  public var hasPostAnalyzerObservations: Bool {return self._postAnalyzerObservations != nil}
  /// Clears the value of `postAnalyzerObservations`. Subsequent reads from it will return its default value.
  public mutating func clearPostAnalyzerObservations() {self._postAnalyzerObservations = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _thumbnail: String? = nil
  fileprivate var _patientID: String? = nil
  fileprivate var _documentDate: String? = nil
  fileprivate var _postAnalyzerObservations: String? = nil
}

/// DocumentAnalysis represents state of document during it's processing state. 
public struct Vault_DocStatus_DocumentAnalysis {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// DocumentSmartReport represent smart report related status of document.
  public var documentSmartReport: Vault_DocStatus_DocumentSmartReport {
    get {return _documentSmartReport ?? Vault_DocStatus_DocumentSmartReport()}
    set {_documentSmartReport = newValue}
  }
  /// Returns true if `documentSmartReport` has been explicitly set.
  public var hasDocumentSmartReport: Bool {return self._documentSmartReport != nil}
  /// Clears the value of `documentSmartReport`. Subsequent reads from it will return its default value.
  public mutating func clearDocumentSmartReport() {self._documentSmartReport = nil}

  /// Document related other info.
  public var documentInfo: Vault_DocStatus_DocumentInfo {
    get {return _documentInfo ?? Vault_DocStatus_DocumentInfo()}
    set {_documentInfo = newValue}
  }
  /// Returns true if `documentInfo` has been explicitly set.
  public var hasDocumentInfo: Bool {return self._documentInfo != nil}
  /// Clears the value of `documentInfo`. Subsequent reads from it will return its default value.
  public mutating func clearDocumentInfo() {self._documentInfo = nil}

  /// Date of the document.
  public var documentDate: String {
    get {return _documentDate ?? String()}
    set {_documentDate = newValue}
  }
  /// Returns true if `documentDate` has been explicitly set.
  public var hasDocumentDate: Bool {return self._documentDate != nil}
  /// Clears the value of `documentDate`. Subsequent reads from it will return its default value.
  public mutating func clearDocumentDate() {self._documentDate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _documentSmartReport: Vault_DocStatus_DocumentSmartReport? = nil
  fileprivate var _documentInfo: Vault_DocStatus_DocumentInfo? = nil
  fileprivate var _documentDate: String? = nil
}

/// DocumentListRequest represents list of document ids for request body. 
public struct Vault_DocStatus_DocumentListRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of document ids.
  public var documents: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Vault_DocStatus_DocumentStatus: @unchecked Sendable {}
extension Vault_DocStatus_DocumentStatus.OneOf_DocumentStatusResponse: @unchecked Sendable {}
extension Vault_DocStatus_NotAccessible: @unchecked Sendable {}
extension Vault_DocStatus_DocumentListResponse: @unchecked Sendable {}
extension Vault_DocStatus_DocumentSmartReport: @unchecked Sendable {}
extension Vault_DocStatus_DocumentInfo: @unchecked Sendable {}
extension Vault_DocStatus_DocumentAnalysis: @unchecked Sendable {}
extension Vault_DocStatus_DocumentListRequest: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vault.doc_status"

extension Vault_DocStatus_DocumentStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DocumentStatus"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "not_accessible"),
    2: .standard(proto: "document_analysis"),
    3: .standard(proto: "document_info"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Vault_DocStatus_NotAccessible?
        var hadOneofValue = false
        if let current = self.documentStatusResponse {
          hadOneofValue = true
          if case .notAccessible(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.documentStatusResponse = .notAccessible(v)
        }
      }()
      case 2: try {
        var v: Vault_DocStatus_DocumentAnalysis?
        var hadOneofValue = false
        if let current = self.documentStatusResponse {
          hadOneofValue = true
          if case .documentAnalysis(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.documentStatusResponse = .documentAnalysis(v)
        }
      }()
      case 3: try {
        var v: Vault_DocStatus_DocumentInfo?
        var hadOneofValue = false
        if let current = self.documentStatusResponse {
          hadOneofValue = true
          if case .documentInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.documentStatusResponse = .documentInfo(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.documentStatusResponse {
    case .notAccessible?: try {
      guard case .notAccessible(let v)? = self.documentStatusResponse else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .documentAnalysis?: try {
      guard case .documentAnalysis(let v)? = self.documentStatusResponse else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .documentInfo?: try {
      guard case .documentInfo(let v)? = self.documentStatusResponse else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_DocStatus_DocumentStatus, rhs: Vault_DocStatus_DocumentStatus) -> Bool {
    if lhs.documentStatusResponse != rhs.documentStatusResponse {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Vault_DocStatus_NotAccessible: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotAccessible"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_DocStatus_NotAccessible, rhs: Vault_DocStatus_NotAccessible) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Vault_DocStatus_DocumentListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DocumentListResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "document_status"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.documentStatus) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.documentStatus.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.documentStatus, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_DocStatus_DocumentListResponse, rhs: Vault_DocStatus_DocumentListResponse) -> Bool {
    if lhs.documentStatus != rhs.documentStatus {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Vault_DocStatus_DocumentSmartReport: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DocumentSmartReport"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "is_smart_report_available"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._isSmartReportAvailable) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._isSmartReportAvailable {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_DocStatus_DocumentSmartReport, rhs: Vault_DocStatus_DocumentSmartReport) -> Bool {
    if lhs._isSmartReportAvailable != rhs._isSmartReportAvailable {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Vault_DocStatus_DocumentInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DocumentInfo"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "thumbnail"),
    2: .standard(proto: "patient_id"),
    3: .same(proto: "tags"),
    4: .standard(proto: "document_date"),
    5: .standard(proto: "post_analyzer_observations"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._thumbnail) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._patientID) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._documentDate) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._postAnalyzerObservations) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._thumbnail {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._patientID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 3)
    }
    try { if let v = self._documentDate {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._postAnalyzerObservations {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_DocStatus_DocumentInfo, rhs: Vault_DocStatus_DocumentInfo) -> Bool {
    if lhs._thumbnail != rhs._thumbnail {return false}
    if lhs._patientID != rhs._patientID {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs._documentDate != rhs._documentDate {return false}
    if lhs._postAnalyzerObservations != rhs._postAnalyzerObservations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Vault_DocStatus_DocumentAnalysis: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DocumentAnalysis"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "document_smart_report"),
    2: .standard(proto: "document_info"),
    3: .standard(proto: "document_date"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._documentSmartReport) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._documentInfo) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._documentDate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._documentSmartReport {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._documentInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._documentDate {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_DocStatus_DocumentAnalysis, rhs: Vault_DocStatus_DocumentAnalysis) -> Bool {
    if lhs._documentSmartReport != rhs._documentSmartReport {return false}
    if lhs._documentInfo != rhs._documentInfo {return false}
    if lhs._documentDate != rhs._documentDate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Vault_DocStatus_DocumentListRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DocumentListRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "documents"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.documents) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.documents.isEmpty {
      try visitor.visitRepeatedStringField(value: self.documents, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Vault_DocStatus_DocumentListRequest, rhs: Vault_DocStatus_DocumentListRequest) -> Bool {
    if lhs.documents != rhs.documents {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
