// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: vault/gmail_sync.proto

package gmail_sync

import (
	cta "github.com/eka-care/proto-contracts/go/vault/cta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents current gmail sync status.
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // State -> Unspecified.
	State_STATE_STARTED     State = 1 // State -> Started.
	State_STATE_PROCESSING  State = 2 // State -> Processing.
	State_STATE_SYNCED      State = 3 // State -> Synced.
	State_STATE_UNLINKED    State = 4 // State -> Unlinked.
	State_STATE_FAILED      State = 5 // State -> Failed.
	State_STATE_REVOKED     State = 6 // State -> Revoked.
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_STARTED",
		2: "STATE_PROCESSING",
		3: "STATE_SYNCED",
		4: "STATE_UNLINKED",
		5: "STATE_FAILED",
		6: "STATE_REVOKED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_STARTED":     1,
		"STATE_PROCESSING":  2,
		"STATE_SYNCED":      3,
		"STATE_UNLINKED":    4,
		"STATE_FAILED":      5,
		"STATE_REVOKED":     6,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_vault_gmail_sync_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_vault_gmail_sync_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_vault_gmail_sync_proto_rawDescGZIP(), []int{0}
}

// GmailSync represents sync status along with pop-up summary.
type GmailSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status          State            `protobuf:"varint,1,opt,name=status,proto3,enum=vault.gmail_sync.State" json:"status,omitempty"`                     // Gmail sync status.
	SyncId          string           `protobuf:"bytes,2,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`                                    // Gmail sync sync id.
	Categories      []*Categories    `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`                                          // Gmail sync profile classification data.
	TotalCount      *uint32          `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`                 // Total count of docs (identified + needs review).
	ProfileDocPopup *ProfileDocPopup `protobuf:"bytes,5,opt,name=profile_doc_popup,json=profileDocPopup,proto3,oneof" json:"profile_doc_popup,omitempty"` // Gmail sync pop-up summary.
	Count           uint32           `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`                                                   // Gmail sync documents count.
}

func (x *GmailSync) Reset() {
	*x = GmailSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_gmail_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GmailSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmailSync) ProtoMessage() {}

func (x *GmailSync) ProtoReflect() protoreflect.Message {
	mi := &file_vault_gmail_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmailSync.ProtoReflect.Descriptor instead.
func (*GmailSync) Descriptor() ([]byte, []int) {
	return file_vault_gmail_sync_proto_rawDescGZIP(), []int{0}
}

func (x *GmailSync) GetStatus() State {
	if x != nil {
		return x.Status
	}
	return State_STATE_UNSPECIFIED
}

func (x *GmailSync) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *GmailSync) GetCategories() []*Categories {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GmailSync) GetTotalCount() uint32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

func (x *GmailSync) GetProfileDocPopup() *ProfileDocPopup {
	if x != nil {
		return x.ProfileDocPopup
	}
	return nil
}

func (x *GmailSync) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Categories represent gmail sync profile classification screen.
type Categories struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabTitle      string `protobuf:"bytes,1,opt,name=tab_title,json=tabTitle,proto3" json:"tab_title,omitempty"`                  // Identified or Needs review tab title.
	TabCount      uint32 `protobuf:"varint,2,opt,name=tab_count,json=tabCount,proto3" json:"tab_count,omitempty"`                 // Number of records found under each tab.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                            // Description of the tab.
	Bgcolor       string `protobuf:"bytes,4,opt,name=bgcolor,proto3" json:"bgcolor,omitempty"`                                    // Background color for the tab.
	TabCountColor string `protobuf:"bytes,5,opt,name=tab_count_color,json=tabCountColor,proto3" json:"tab_count_color,omitempty"` // Color for tab count.
}

func (x *Categories) Reset() {
	*x = Categories{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_gmail_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Categories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categories) ProtoMessage() {}

func (x *Categories) ProtoReflect() protoreflect.Message {
	mi := &file_vault_gmail_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categories.ProtoReflect.Descriptor instead.
func (*Categories) Descriptor() ([]byte, []int) {
	return file_vault_gmail_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Categories) GetTabTitle() string {
	if x != nil {
		return x.TabTitle
	}
	return ""
}

func (x *Categories) GetTabCount() uint32 {
	if x != nil {
		return x.TabCount
	}
	return 0
}

func (x *Categories) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Categories) GetBgcolor() string {
	if x != nil {
		return x.Bgcolor
	}
	return ""
}

func (x *Categories) GetTabCountColor() string {
	if x != nil {
		return x.TabCountColor
	}
	return ""
}

// ProfileDocPopup represents gmail sync pop-up summary.
type ProfileDocPopup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cta   *cta.CTA `protobuf:"bytes,1,opt,name=cta,proto3" json:"cta,omitempty"`     // CTA configuration for button.
	Title string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // No. of records belonging to tab.
}

func (x *ProfileDocPopup) Reset() {
	*x = ProfileDocPopup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_gmail_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileDocPopup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDocPopup) ProtoMessage() {}

func (x *ProfileDocPopup) ProtoReflect() protoreflect.Message {
	mi := &file_vault_gmail_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileDocPopup.ProtoReflect.Descriptor instead.
func (*ProfileDocPopup) Descriptor() ([]byte, []int) {
	return file_vault_gmail_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileDocPopup) GetCta() *cta.CTA {
	if x != nil {
		return x.Cta
	}
	return nil
}

func (x *ProfileDocPopup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_vault_gmail_sync_proto protoreflect.FileDescriptor

var file_vault_gmail_sync_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x79,
	0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e,
	0x67, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x1a, 0x0f, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x2f, 0x63, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x02, 0x0a, 0x09,
	0x47, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x2e, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x79,
	0x6e, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6e,
	0x63, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e,
	0x67, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x24, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x52, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x64, 0x6f, 0x63, 0x5f, 0x70, 0x6f, 0x70, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x67, 0x6d, 0x61, 0x69, 0x6c,
	0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x63,
	0x50, 0x6f, 0x70, 0x75, 0x70, 0x48, 0x01, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x44, 0x6f, 0x63, 0x50, 0x6f, 0x70, 0x75, 0x70, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x6f,
	0x63, 0x5f, 0x70, 0x6f, 0x70, 0x75, 0x70, 0x22, 0xaa, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x62, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x62, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x67, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x67, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0f,
	0x74, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x61, 0x62, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x4c, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44,
	0x6f, 0x63, 0x50, 0x6f, 0x70, 0x75, 0x70, 0x12, 0x23, 0x0a, 0x03, 0x63, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x54, 0x41, 0x52, 0x03, 0x63, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x2a, 0x92, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x59, 0x4e, 0x43, 0x45, 0x44, 0x10, 0x03, 0x12, 0x12,
	0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4c, 0x49, 0x4e, 0x4b, 0x45, 0x44,
	0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x56, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0x06, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x61, 0x2d, 0x63, 0x61, 0x72, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x67,
	0x6f, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x79,
	0x6e, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vault_gmail_sync_proto_rawDescOnce sync.Once
	file_vault_gmail_sync_proto_rawDescData = file_vault_gmail_sync_proto_rawDesc
)

func file_vault_gmail_sync_proto_rawDescGZIP() []byte {
	file_vault_gmail_sync_proto_rawDescOnce.Do(func() {
		file_vault_gmail_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_vault_gmail_sync_proto_rawDescData)
	})
	return file_vault_gmail_sync_proto_rawDescData
}

var file_vault_gmail_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vault_gmail_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vault_gmail_sync_proto_goTypes = []interface{}{
	(State)(0),              // 0: vault.gmail_sync.State
	(*GmailSync)(nil),       // 1: vault.gmail_sync.GmailSync
	(*Categories)(nil),      // 2: vault.gmail_sync.Categories
	(*ProfileDocPopup)(nil), // 3: vault.gmail_sync.ProfileDocPopup
	(*cta.CTA)(nil),         // 4: vault.common.CTA
}
var file_vault_gmail_sync_proto_depIdxs = []int32{
	0, // 0: vault.gmail_sync.GmailSync.status:type_name -> vault.gmail_sync.State
	2, // 1: vault.gmail_sync.GmailSync.categories:type_name -> vault.gmail_sync.Categories
	3, // 2: vault.gmail_sync.GmailSync.profile_doc_popup:type_name -> vault.gmail_sync.ProfileDocPopup
	4, // 3: vault.gmail_sync.ProfileDocPopup.cta:type_name -> vault.common.CTA
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vault_gmail_sync_proto_init() }
func file_vault_gmail_sync_proto_init() {
	if File_vault_gmail_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vault_gmail_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GmailSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_gmail_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Categories); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_gmail_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileDocPopup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vault_gmail_sync_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vault_gmail_sync_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vault_gmail_sync_proto_goTypes,
		DependencyIndexes: file_vault_gmail_sync_proto_depIdxs,
		EnumInfos:         file_vault_gmail_sync_proto_enumTypes,
		MessageInfos:      file_vault_gmail_sync_proto_msgTypes,
	}.Build()
	File_vault_gmail_sync_proto = out.File
	file_vault_gmail_sync_proto_rawDesc = nil
	file_vault_gmail_sync_proto_goTypes = nil
	file_vault_gmail_sync_proto_depIdxs = nil
}
