syntax = "proto3";

package vault.added_records_summary;

import "vault/gmail_sync.proto";

option go_package = "github.com/eka-care/proto-contracts/go/vault/addrecsummary";

/* Status represents health bottom sheet and gmail sync status. */
message Status {
  oneof Response {
    SyncRecords sync_records = 1; // Adding records to Health Locker.
    AnalyzingRecords analyzing_records = 2; // Analyzing your health records (X).
    EndState end_state = 3; // Making it simpler to see your health.
  }
}

/* Sync Records represents the state when records are added to health locker. */
message SyncRecords {
  vault.gmail_sync.GmailSync gmail_sync = 1; // Gmail sync records found, count is required field.
}

/* AnalyzingRecords represents smart report extraction state of documents. */
message AnalyzingRecords {
  uint32 count = 1; // Total count i.e. manual upload + gmail sync upload.
  optional vault.gmail_sync.GmailSync gmail_sync = 2; // Gmail sync records found, count is required field.
}

/* EndState represents gmail sync completion and smart report extraction. */
message EndState {
  optional vault.gmail_sync.GmailSync gmail_sync = 1; // Gmail sync records found, count is required field.
  Summary summary = 2; // View my health bottom sheet.
}

/* Summary represents health summary bottom sheet. */
message Summary {
  message VitalsInfo {
    uint32 vitals_found = 1; // Total vitals found for current upload.
    optional uint32 concerns = 2; // Concerned vitals.
    optional uint32 trends_updated = 3; // Trends updated count.
    optional uint32 latest_added = 4; // Latest added trends from current upload.
  }
  optional VitalsInfo vitals_info = 1; // Vitals related info.
  uint32 records_count = 2; // Total number of documents uploaded.
}
