syntax = "proto3";

package vault.banners;

import "vault/cta.proto";
import "vault/banner_body_parameter.proto";

option go_package = "github.com/eka-care/proto-contracts/go/vault/banners";

/* BannersResponse represents banners on records page such as gmail sync,
 * insights etc. */
message BannersResponse {
  /* Banner represents multiple banner on the records screen. */
  repeated Banner banners = 1;
}

/* Banner represents configuration. */
message Banner {
  string title = 1;         // Title of the banner.
  optional string body = 2; // Body or description of the banner.
  vault.common.CTA cta = 3; // CTA configuration for button.
  string colour = 4;        // Colour of the banner in hex code.
  string iconBackgroundColor = 5; // Color of icon background in hex code.
  string tagBackgroundColor = 6; // Color of tag background in hex code.
  string tagTitleColor = 7; // Color of tag title in hex code.
  oneof image {
    string img = 8;    // Image link for the banner.
    string lottie = 9; // Lottie link for the banner.
  }
  repeated vault.banner_body_parameter.BannerBodyParameter body_parameters =
      10;                         // dynamic parameters with body.
  optional string banner_id = 11; // ID represents banner/card identifier.
}
