syntax = "proto3";
package vault.banners;

import "banner_body_parameter.proto";

option go_package = "github.com/eka-care/proto-contracts/go/vault/banners";

/* BannersResponse represents banners on records page such as gmail sync, insights etc. */
message BannersResponse {
  /* Banner represents multiple banner on the records screen. */
  repeated Banner banners = 1;
}

/* BannerCTAParams represents cta params. */
message BannerCTAParams {
  optional string url=3; // URL to redirect the page.
  repeated string document_ids=4; // Document_ids represent the list of documents.
  optional string id=5; // ID represent page ID.
  optional string email_id=6; // Email_ID refers to gmail sync email id.
}

/* BannerCTA represents cta of banners*/
message BannerCTA {
  string id = 1; // ID represent page ID.
  string action = 2; // Title of the source click block.
  string title  = 3;// Action applied on click.
  BannerCTAParams params = 4;// BannerCTAParams represents cta params.
}

/* Banner represents configuration. */
message Banner {
  string title = 1; // Title of the banner.
  optional string body = 2; // Body or description of the banner.
  BannerCTA cta = 3; // CTA configuration for button.
  string colour = 4; // Colour of the banner in hex code.
  oneof image {
    string img = 5; // Image link for the banner.
    string lottie = 6; // Lottie link for the banner.
  }
  repeated vault.banner_body_parameter.BannerBodyParameter body_parameters = 7;                             // dynamic parameters with body.
  optional string id = 8; // ID represents banner/card identifier.
}