syntax = "proto3";

package vault.doc_status;

option go_package = "github.com/eka-care/proto-contracts/go/vault/docstatus";

/* DocumentStatus represents status of given document id list. */
message DocumentStatus {
  oneof DocumentStatusResponse {
    DocumentAccessible document_accessible_info = 1;  // DocumentAccessible represent document 
                                                      // upload status and related fields.
    DocumentInfo document_info = 2;                   // DocumentInfo represents document related other info.
  } 
}

/* DocumentListResponse represents response for the list of documents in processing. */
message DocumentListResponse {
  repeated DocumentStatus document_status = 1; // Status of requested document ids.
}

/* DocumentSmartReport represents smart report status*/
message DocumentSmartReport {
  bool is_analyzing = 1;              // Represents if document is in processing.
  bool is_smart_report_available = 2; // Represents if document is a smart report.
  optional string document_date = 3;  // Date of the document (lab report, prescription).
}

/* DocumentInfo represents document related other info. */
message DocumentInfo {
  optional string thumbnail = 1;                   // Thumbnail of the lab report.
  optional string patient_id = 2;                  // OID of the patient on document.
  repeated string tags = 3;                        // Derived tags of the document.
  optional string post_analyzer_observations = 4;  // Confirm the scanned data message.
}

/* DocumentAccessible represents if document is uploaded to server and processing of it. */
message DocumentAccessible {
  bool is_accessible = 1;                        // Is_accessible represents if document is uploaded to server or not.
  DocumentSmartReport document_smart_report = 2; // DocumentSmartReport represent smart report related status of document.
  DocumentInfo document_info = 3;                // Document related other info.
}

/* DocumentListRequest represents list of document ids for request body. */
message DocumentListRequest {
  repeated string documents = 1; // List of document ids.
}
