syntax = "proto3";
     
package vault.documents;

option go_package = "github.com/eka-care/proto-contracts/go/vault/documents";

/* Document type suggests type of document uploaded to the vault. */
enum DocumentType {
    DOCUMENT_TYPE_UNSPECIFIED = 0; // DocumentType -> Unspecified.
  
    DOCUMENT_TYPE_LAB_REPORT = 1; // DocumentType -> Lab report.
  
    DOCUMENT_TYPE_PRESCRIPTION = 2; // DocumentType -> Prescription.
    DOCUMENT_TYPE_OTHERS = 3;       // DocumentType -> Other.
}

/* FileType of the uploaded document.*/
enum FileType {
  FILETYPE_UNSPECIFIED = 0; // FileType -> Unspecified.
  FILETYPE_IMG = 1;         // FileType -> Image file.
  FILETYPE_PDF = 2;         // FileType -> PDF file.
}

/* List of documents along with the offset to fetch next page document list. */
message DocumentList {
    repeated Document documents = 1;
    optional string offset = 2;
}

/* Document describes attributes of vault document. */
message Document {
  string patient_name = 1;                  // Patient name of the uploaded vault document.
  string oid = 2;                           // Profile ID.
  string document_id = 3;                   // Document ID.
  DocumentType document_type = 4;           // Type of the uploaded document.
  string thumbnail = 5;                     // Thumbnail url of the document.
  bool shareable = 6;                       // Is the document shareable with doctors.
  uint32 files_count = 7;                   // Number of files in the document.
  string desc = 8;                          // Description on the document uploaded.
  bool can_delete = 9;                      // Document deletion allowed flag.
  bool is_smart_report_available = 10;      // Is the uploaded document a medical lab report.
  bool is_analyzing = 11;                   // Document still in analysis process of a smart report.
  bool is_processing = 12;                  // Is document in processing state.
  FileType file_type = 13;                  // Type of document uploaded, IMG or PDF.
  uint32 created_at = 14;                   // Time at which the document was created or uploaded.
  repeated string content_type = 15;        // Content type of the document.
  uint32 document_date = 16;                // Date of the lab-report or prescription or other.
  repeated string user_tags = 17;           // User added tags for the document.
  repeated string dervied_tags = 18;        // Tags derived based on the vitals in the document.
  string post_analyzer_observations = 19;   // Post analyzer observations.
  optional bool is_encrypted = 20;          // Is the document part of secret vault.
  optional GetFileResponse file = 21;       // GetFileResponse describes file of the uploaded document.
  optional string hip_id = 22;              // Provider ID.
  optional bool health_id = 23;             // Document linked with ABHA ID.
  DoctorResponse doctor_response = 24;      // Doctor related document response.
}

/* DoctorResponse represent doctor related attributes for document response. */
message DoctorResponse {
  string doctor_id = 1;                     // Doctor ID.
  string clinic_id = 2;                     // Clinic ID.
  optional bool uploaded_by_me = 3;         // If the document is uploaded by the doctor.
  repeated string shared_with = 4;          // Document shared with list of doctors.
  optional SearchMetaData search_meta = 5;  // Search meta defines page number, file, highlight of the document.
}

/* GetFileResponse describes files under the document. */
message GetFileResponse {
  string asset_url = 1;    // Asset uri of the uploaded document.
  string file_type = 2;    // File type of the uploaded document.
  string share_text = 3;   // Share text of the uploaded document.
}

/* SearchMetaData describes the metadata within the smart report.*/
message SearchMetaData  {
  string highlight = 1; // Highlight a vital.
  uint32 page = 2;      // Page of the report.
  uint32 file_num = 3;  // File number within the document.
}