syntax = "proto3";

package vault.features;

import "vault/cta.proto";
import "vault/features.proto";

option go_package = "github.com/eka-care/proto-contracts/go/vault/features";

message FeatureIcon {
  Feature type = 1;
  vault.common.CTA cta = 2;
}

message FeatureIconsResponse { repeated FeatureIcon icons = 1; }

message FeatureIconsAPIResponse {
  /* ErrorCode represents list of errors */
  enum ErrorCode {
    ERROR_UNSPECIFIED = 0; // Error -> Unspecified.
  }

  /* Error represents error resonse of API */
  message Error {
    ErrorCode code = 1; // Error Code.
    string message = 2; // Error Message.
  }

  oneof result {
    FeatureIconsResponse response = 1;
    Error error = 2;
  }
}

message MyHealthFeatureIconResponse { int32 total_vitals = 1; }

message FeatureIconStatusResponse {
  oneof result { MyHealthFeatureIconResponse my_health = 1; }
}

message FeatureIconStatusAPIResponse {
  /* ErrorCode represents list of errors */
  enum ErrorCode {
    ERROR_UNSPECIFIED = 0; // Error -> Unspecified.
  }

  /* Error represents error resonse of API */
  message Error {
    ErrorCode code = 1; // Error Code.
    string message = 2; // Error Message.
  }

  oneof result {
    FeatureIconStatusResponse response = 1;
    Error error = 2;
  }
}