syntax = "proto3";

package vault.insights;

import "google/protobuf/timestamp.proto";
import "vault/range.proto";

option go_package = "github.com/eka-care/proto-contracts/go/vault/insights";

/* VitalInsightsResponse represents insights
response */
message VitalInsightsResponse {
  message Coordinate {
    double value = 1; // Value of vital.
    double count = 2; // Number of data points (users) for the concerned value.
  }

  message Axis {
    optional string title = 1; // Title for the axis.
  }

  message Axes {
    optional Axis x = 1; // X Axis.
    optional Axis y = 2; // Y Axis.
  }

  message Insight {
    string title = 1;                    // Title for the insight.
    string body = 2;                     // Body for the insight.
    repeated Coordinate coordinates = 3; // Coordinates for the histogram.
    string type = 4;                     // Type of the insight.
    LatestValue latest_value = 5;        // Latest Value of the vital.
    optional string name = 6;            // Display Name of the vital.
    optional string test_eka_id = 7;     // Test Eka ID of the vital.
    optional string unit = 8;            // Normalised Unit of the vital.
    optional Axes axes = 9;              // Axes of plot.
  }

  enum Interpretation {
    INTERPRETATION_UNSPECIFIED = 0; // Interpretation -> Unspecified.

    INTERPRETATION_NORMAL = 1; // Interpretation -> Normal.

    INTERPRETATION_CRITICALLY_HIGH = 2; // Interpretation -> Critically High.
    INTERPRETATION_VERY_HIGH = 3;       // Interpretation -> Very High.
    INTERPRETATION_HIGH = 4;            // Interpretation -> High.
    INTERPRETATION_BORDERLINE_HIGH = 5; // Interpretation -> Borderline High.

    INTERPRETATION_CRITICALLY_LOW = 6; // Interpretation -> Critically Low.
    INTERPRETATION_VERY_LOW = 7;       // Interpretation -> Very Low.
    INTERPRETATION_LOW = 8;            // Interpretation -> Low.
    INTERPRETATION_BORDERLINE_LOW = 9; // Interpretation -> Borderline Low.

    INTERPRETATION_ABNORMAL = 10;     // Interpretation -> Abnormal.
    INTERPRETATION_UNDETERMINED = 11; // Interpretation -> Undertermined.
  }

  message AddLatestDataPrompt {
    optional string text = 1; // Title for the prompt.
  }

  message LatestValue {
    double value = 1;                          // Latest value.
    google.protobuf.Timestamp result_date = 2; // Timestamp of latest value.
    string display_result_date = 3; // Display timestamp of latest value.
    optional AddLatestDataPrompt add_latest_data_prompt =
        4;                                 // Prompt for adding latest data.
    double latest_value_y_coordinate = 5;  // Y coordinate of the latest value.
    optional Interpretation result_id = 6; // Interpretation of latest value.
    optional vault.common.ValueRange normal_range =
        7; // Normal range of the vital.
  }

  repeated Insight insights = 1; // Insights for the vital.
}

/* VitalInsightsListResponse represents insights list
response */
message VitalInsightsListResponse {
  repeated VitalInsightsResponse.Insight insights = 1; // Insights.
  optional string token = 2; // Token for the next page.
}