syntax = "proto3";

package vault.insurance;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/eka-care/proto-contracts/go/vault/insurance";

/* InsuranceResponse */
message InsuranceResponse {
  string job_id = 1;
  string meta = 2; // metadata.
  InsuranceData response = 3;
}

/* InsuranceData represents . */
message InsuranceData {
  optional LinkedInsurerProviderEntity insurance_provider = 1;
  optional InsuranceType insurance_type = 2;
  optional PlanDetails plan_details = 3;
  optional PolicyDetails policy_details = 4;
}

message InsuranceType {
  float confidence = 1;
  Type value = 2;

  enum Type {
    TYPE_UNSPECIFIED = 0; // Unspecified.
    TYPE_HEALTH = 1;      // Health.
    TYPE_LIFE = 2;        // Life.
    TYPE_VEHICLE = 3;        // vehicle.
    TYPE_TRAVEL = 4;        // travel.
  }
}

message CoverageDetails {
  optional EntityNumber premium_amount = 1;
  optional PremiumFrequency premium_payment_frequency = 2;
  optional EntityNumber sum_insured = 3;
}

message PremiumFrequency {
  float confidence = 1;
  Type value = 2;

  enum Type {
    TYPE_UNSPECIFIED = 0; // Unspecified.
    TYPE_YEARLY = 1;      // Yearly.
  }
}

message PolicyDetails {
  optional Entity policy_number = 1;
  optional PolicyDate policy_dates = 2;
  optional CoverageDetails coverage_details = 3;
  repeated Members insured_members = 4;

  message Members {
    optional EntityNumber age = 1;
    optional EntityGender gender = 2;
    optional Entity name = 3;
    optional EntityTimestamp dob = 4;
  }
}

message PlanDetails {
  optional Entity plan_name = 1;
  optional Entity addon_plan_name = 2;
  optional Entity rider_name = 3;
  optional Entity uin_number = 4;
}

message PolicyDate {
  optional EntityTimestamp policy_end_date = 3;
  optional EntityTimestamp policy_issued_date = 1;
  optional EntityTimestamp policy_start_date = 2;
}

message EntityTimestamp {
  float confidence = 1;
  google.protobuf.Timestamp value = 2;
}

message Entity {
  float confidence = 1;
  string value = 2;
}

message LinkedInsurerProviderEntity {
  float confidence = 1;
  string value = 2;
  Type linked_value = 3;
  enum Type {
    TYPE_UNSPECIFIED = 0; // Unspecified
    TYPE_ACKO = 1;
    TYPE_ADITYA = 2;
    TYPE_APOLLO = 3;
    TYPE_BAJAJ_GENERAL = 4;
    TYPE_BHARTI = 5;
    TYPE_CARE_HEALTH = 6;
    TYPE_CHOLAMANDALAM = 7;
    TYPE_CIGNA = 8 [deprecated = true];
    TYPE_DHFL = 9;
    TYPE_EDELWEISS = 10;
    TYPE_FUTURE_GENERALI = 11;
    TYPE_DIGIT = 12;
    TYPE_HDFC_ERGO = 13;
    TYPE_HDFC_ERGO_HEALTH = 14 [deprecated = true]; 
    TYPE_ICICI_LOMBARD = 15;
    TYPE_IFFCO = 16;
    TYPE_KOTAK_GENERAL = 17;
    TYPE_LNT = 18;
    TYPE_LIBERTY = 19;
    TYPE_MAGMA = 20;
    TYPE_MANIPAL_CIGNA = 21;
    TYPE_NATIONAL_INSURANCE = 22;
    TYPE_NAVI = 23;
    TYPE_BUPA = 24;
    TYPE_ORIENTAL = 25;
    TYPE_RAHEJA = 26;
    TYPE_RELIANCE_GENERAL = 27;
    TYPE_RELIANCE_HEALTH = 28 [deprecated = true];
    TYPE_RELIGARE = 29;
    TYPE_ROYAL_SUNDARAM = 30;
    TYPE_SBI_GENERAL = 31;
    TYPE_SHRIRAM_GENERAL = 32;
    TYPE_STAR = 33;
    TYPE_TATA_AIG = 34;
    TYPE_INDIA_ASSURANCE = 35;
    TYPE_UNITED_INDIA = 36;
    TYPE_SOMPO = 37;
    TYPE_LIC = 38;
    TYPE_SBI_LIFE = 39;
    TYPE_ICICI_PRUDENTIAL = 40;
    TYPE_PNB_METLIFE = 41;
    TYPE_MAX_LIFE = 42;
    TYPE_AEGON_LIFE = 43;
    TYPE_SHRIRAM_LIFE = 44;
    TYPE_TATA_AIA = 45;
    TYPE_INDIA_FIRST_LIFE = 46;
    TYPE_RELIANCE_NIPPON = 47;
    TYPE_KOTAK_LIFE = 48;
    TYPE_HDFC_LIFE = 49;
    TYPE_BAJAJ_LIFE = 50;
  }
}

message EntityNumber {
  float confidence = 1;
  float value = 2;
}

message EntityGender {
  float confidence = 1;
  Type value = 2;

  enum Type {
    TYPE_UNSPECIFIED = 0; // Unspecified.
    TYPE_MALE = 1;        // Male.
    TYPE_FEMALE = 2;      // Female
  }
}
