syntax = "proto3";

package vault.records;

option go_package = "github.com/eka-care/proto-contracts/go/vault/records";

enum SizeUnit {
  SIZE_UNIT_UNSPECIFIED = 0; // Size Unit -> Unspecified.
  SIZE_UNIT_GB = 1;          // Size Unit -> GB.
  SIZE_UNIT_MB = 2;          // Size Unit -> MB.
  SIZE_UNIT_KB = 3;          // Size Unit -> KB.
  SIZE_UNIT_B = 4;           // Size Unit -> B.
  SIZE_UNIT_TB = 5;          // Size Unit -> TB.
  SIZE_UNIT_PB = 6;          // Size Unit -> PB.
  SIZE_UNIT_EB = 7;          // Size Unit -> EB.
  SIZE_UNIT_ZB = 8;          // Size Unit -> ZB.
}

enum Status {
  STATUS_UNSPECIFIED = 0;  // Status -> Unspecified.
  STATUS_WITHIN_LIMIT = 1; // Status -> OK.
  STATUS_NEAR_LIMIT = 2;   // Status -> Warning.
  STATUS_EXCEEDED = 3;     // Status -> Exceeded.
}

message Usage {
  string amount = 1; // Value.
  SizeUnit unit = 2; // Unit.
  Status status = 3; // Status.
}

message Exceeded {
  string amount = 1; // Value.
  SizeUnit unit = 2; // Unit.
}

message MaxLimit {
  string amount = 1; // Value.
  SizeUnit unit = 2; // Unit.
}

message Storage {
  Usage usage = 1; // Usage.
  optional Exceeded exceeded =
      2; // This key will be absent if usage.status is not "EXCEEDED".
  MaxLimit max_limit = 3; // Max Limit.
}

/* RecordsResponse represents list of records. */
message RecordsStorageDataResponse {
  Storage storage = 1; // Storage.
}

/* RecordsStorageAPIResponse represents api response of records storage. */
message RecordsStorageAPIResponse {
  /* ErrorCode represents list of errors */
  enum ErrorCode {
    ERROR_UNSPECIFIED = 0; // Error -> Unspecified.
  }

  /* Error represents error resonse of API */
  message Error {
    ErrorCode code = 1; // Error Code.
    string message = 2; // Error Message.
  }

  oneof result {
    RecordsStorageDataResponse response = 1;
    Error error = 2;
  }
}