# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault/added_records_summary.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vault import gmail_sync_pb2 as vault_dot_gmail__sync__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!vault/added_records_summary.proto\x12\x1bvault.added_records_summary\x1a\x16vault/gmail_sync.proto\"\xde\x01\n\x06Status\x12@\n\x0csync_records\x18\x01 \x01(\x0b\x32(.vault.added_records_summary.SyncRecordsH\x00\x12J\n\x11\x61nalyzing_records\x18\x02 \x01(\x0b\x32-.vault.added_records_summary.AnalyzingRecordsH\x00\x12:\n\tend_state\x18\x03 \x01(\x0b\x32%.vault.added_records_summary.EndStateH\x00\x42\n\n\x08Response\"\r\n\x0bSyncRecords\"f\n\x10\x41nalyzingRecords\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\x34\n\ngmail_sync\x18\x02 \x01(\x0b\x32\x1b.vault.gmail_sync.GmailSyncH\x00\x88\x01\x01\x42\r\n\x0b_gmail_sync\"\x86\x01\n\x08\x45ndState\x12\x34\n\ngmail_sync\x18\x01 \x01(\x0b\x32\x1b.vault.gmail_sync.GmailSyncH\x00\x88\x01\x01\x12\x35\n\x07summary\x18\x02 \x01(\x0b\x32$.vault.added_records_summary.SummaryB\r\n\x0b_gmail_sync\"\xa0\x02\n\x07Summary\x12I\n\x0bvitals_info\x18\x01 \x01(\x0b\x32/.vault.added_records_summary.Summary.VitalsInfoH\x00\x88\x01\x01\x12\x15\n\rrecords_count\x18\x02 \x01(\r\x1a\xa2\x01\n\nVitalsInfo\x12\x14\n\x0cvitals_found\x18\x01 \x01(\r\x12\x15\n\x08\x63oncerns\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x1b\n\x0etrends_updated\x18\x03 \x01(\rH\x01\x88\x01\x01\x12\x19\n\x0clatest_added\x18\x04 \x01(\rH\x02\x88\x01\x01\x42\x0b\n\t_concernsB\x11\n\x0f_trends_updatedB\x0f\n\r_latest_addedB\x0e\n\x0c_vitals_infoB<Z:github.com/eka-care/proto-contracts/go/vault/addrecsummaryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault.added_records_summary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/eka-care/proto-contracts/go/vault/addrecsummary'
  _globals['_STATUS']._serialized_start=91
  _globals['_STATUS']._serialized_end=313
  _globals['_SYNCRECORDS']._serialized_start=315
  _globals['_SYNCRECORDS']._serialized_end=328
  _globals['_ANALYZINGRECORDS']._serialized_start=330
  _globals['_ANALYZINGRECORDS']._serialized_end=432
  _globals['_ENDSTATE']._serialized_start=435
  _globals['_ENDSTATE']._serialized_end=569
  _globals['_SUMMARY']._serialized_start=572
  _globals['_SUMMARY']._serialized_end=860
  _globals['_SUMMARY_VITALSINFO']._serialized_start=682
  _globals['_SUMMARY_VITALSINFO']._serialized_end=844
# @@protoc_insertion_point(module_scope)
