# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault/banner_body_parameter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!vault/banner_body_parameter.proto\x12\x1bvault.banner_body_parameter*P\n\x13\x42\x61nnerBodyParameter\x12\x1e\n\x1a\x42ODY_PARAMETER_UNSPECIFIED\x10\x00\x12\x19\n\x15\x42ODY_PARAMETER_MOBILE\x10\x01\x42\x42Z@github.com/eka-care/proto-contracts/go/vault/bannerbodyparameterb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault.banner_body_parameter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z@github.com/eka-care/proto-contracts/go/vault/bannerbodyparameter'
  _BANNERBODYPARAMETER._serialized_start=66
  _BANNERBODYPARAMETER._serialized_end=146
# @@protoc_insertion_point(module_scope)
