# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vault/identical_docs.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vault/identical_docs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avault/identical_docs.proto\x12\x14vault.identical_docs\"u\n\x11IdenticalDocsById\x12\x31\n\tdocuments\x18\x01 \x03(\x0b\x32\x1e.vault.identical_docs.Document\x12\x13\n\x06offset\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05title\x18\x03 \x01(\tB\t\n\x07_offset\"W\n\x08\x44ocument\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x15\n\rdocument_type\x18\x02 \x01(\t\x12\x11\n\tthumbnail\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x04 \x01(\t\"v\n\x14ListAllIdenticalDocs\x12>\n\tdocuments\x18\x01 \x03(\x0b\x32+.vault.identical_docs.IdenticalDocumentInfo\x12\x13\n\x06offset\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_offset\"n\n\x15IdenticalDocumentInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1d\n\x15\x64uplicates_count_desc\x18\x02 \x01(\t\x12\x11\n\tthumbnail\x18\x03 \x01(\t\x12\x17\n\x0f\x64oc_upload_desc\x18\x04 \x01(\tB<Z:github.com/eka-care/proto-contracts/go/vault/identicaldocsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault.identical_docs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/eka-care/proto-contracts/go/vault/identicaldocs'
  _globals['_IDENTICALDOCSBYID']._serialized_start=52
  _globals['_IDENTICALDOCSBYID']._serialized_end=169
  _globals['_DOCUMENT']._serialized_start=171
  _globals['_DOCUMENT']._serialized_end=258
  _globals['_LISTALLIDENTICALDOCS']._serialized_start=260
  _globals['_LISTALLIDENTICALDOCS']._serialized_end=378
  _globals['_IDENTICALDOCUMENTINFO']._serialized_start=380
  _globals['_IDENTICALDOCUMENTINFO']._serialized_end=490
# @@protoc_insertion_point(module_scope)
