# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vault/interpretation.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vault/interpretation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avault/interpretation.proto\x12\x0cvault.vitals*\x83\x03\n\x0eInterpretation\x12\x1e\n\x1aINTERPRETATION_UNSPECIFIED\x10\x00\x12\x19\n\x15INTERPRETATION_NORMAL\x10\x01\x12\"\n\x1eINTERPRETATION_CRITICALLY_HIGH\x10\x02\x12\x1c\n\x18INTERPRETATION_VERY_HIGH\x10\x03\x12\x17\n\x13INTERPRETATION_HIGH\x10\x04\x12\"\n\x1eINTERPRETATION_BORDERLINE_HIGH\x10\x05\x12!\n\x1dINTERPRETATION_CRITICALLY_LOW\x10\x06\x12\x1b\n\x17INTERPRETATION_VERY_LOW\x10\x07\x12\x16\n\x12INTERPRETATION_LOW\x10\x08\x12!\n\x1dINTERPRETATION_BORDERLINE_LOW\x10\t\x12\x1b\n\x17INTERPRETATION_ABNORMAL\x10\n\x12\x1f\n\x1bINTERPRETATION_UNDETERMINED\x10\x0b\x42\x44ZBgithub.com/eka-care/proto-contracts/go/vault/vitals/interpretationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault.interpretation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/eka-care/proto-contracts/go/vault/vitals/interpretation'
  _globals['_INTERPRETATION']._serialized_start=45
  _globals['_INTERPRETATION']._serialized_end=432
# @@protoc_insertion_point(module_scope)
