# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault/key_vitals.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vault import interpretation_pb2 as vault_dot_interpretation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16vault/key_vitals.proto\x12\x0fvault.keyvitals\x1a\x1avault/interpretation.proto\"A\n\x14KeyVitalsAPIResponse\x12)\n\x06vitals\x18\x01 \x03(\x0b\x32\x19.vault.keyvitals.KeyVital\"\x98\x02\n\x08KeyVital\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0btest_eka_id\x18\x02 \x01(\t\x12\x33\n\x05value\x18\x03 \x01(\x0b\x32\x1f.vault.keyvitals.KeyVital.ValueH\x00\x88\x01\x01\x1a\xa9\x01\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\x12\x11\n\x04unit\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x34\n\tresult_id\x18\x03 \x01(\x0e\x32\x1c.vault.vitals.InterpretationH\x02\x88\x01\x01\x12\x15\n\x0bmeasured_at\x18\x04 \x01(\tH\x00\x12\x10\n\x06is_old\x18\x05 \x01(\x08H\x00\x42\x08\n\x06resultB\x07\n\x05_unitB\x0c\n\n_result_idB\x08\n\x06_valueB8Z6github.com/eka-care/proto-contracts/go/vault/keyvitalsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault.key_vitals_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/eka-care/proto-contracts/go/vault/keyvitals'
  _KEYVITALSAPIRESPONSE._serialized_start=71
  _KEYVITALSAPIRESPONSE._serialized_end=136
  _KEYVITAL._serialized_start=139
  _KEYVITAL._serialized_end=419
  _KEYVITAL_VALUE._serialized_start=240
  _KEYVITAL_VALUE._serialized_end=409
# @@protoc_insertion_point(module_scope)
