# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault/storage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vault/storage.proto\x12\rvault.records\"e\n\x05Usage\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12%\n\x04unit\x18\x02 \x01(\x0e\x32\x17.vault.records.SizeUnit\x12%\n\x06status\x18\x03 \x01(\x0e\x32\x15.vault.records.Status\"A\n\x08\x45xceeded\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12%\n\x04unit\x18\x02 \x01(\x0e\x32\x17.vault.records.SizeUnit\"A\n\x08MaxLimit\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12%\n\x04unit\x18\x02 \x01(\x0e\x32\x17.vault.records.SizeUnit\"\x97\x01\n\x07Storage\x12#\n\x05usage\x18\x01 \x01(\x0b\x32\x14.vault.records.Usage\x12.\n\x08\x65xceeded\x18\x02 \x01(\x0b\x32\x17.vault.records.ExceededH\x00\x88\x01\x01\x12*\n\tmax_limit\x18\x03 \x01(\x0b\x32\x17.vault.records.MaxLimitB\x0b\n\t_exceeded\"E\n\x1aRecordsStorageDataResponse\x12\'\n\x07storage\x18\x01 \x01(\x0b\x32\x16.vault.records.Storage\"\xa5\x02\n\x19RecordsStorageAPIResponse\x12=\n\x08response\x18\x01 \x01(\x0b\x32).vault.records.RecordsStorageDataResponseH\x00\x12?\n\x05\x65rror\x18\x02 \x01(\x0b\x32..vault.records.RecordsStorageAPIResponse.ErrorH\x00\x1aZ\n\x05\x45rror\x12@\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x32.vault.records.RecordsStorageAPIResponse.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\tErrorCode\x12\x15\n\x11\x45RROR_UNSPECIFIED\x10\x00\x42\x08\n\x06result*\xb4\x01\n\x08SizeUnit\x12\x19\n\x15SIZE_UNIT_UNSPECIFIED\x10\x00\x12\x10\n\x0cSIZE_UNIT_GB\x10\x01\x12\x10\n\x0cSIZE_UNIT_MB\x10\x02\x12\x10\n\x0cSIZE_UNIT_KB\x10\x03\x12\x0f\n\x0bSIZE_UNIT_B\x10\x04\x12\x10\n\x0cSIZE_UNIT_TB\x10\x05\x12\x10\n\x0cSIZE_UNIT_PB\x10\x06\x12\x10\n\x0cSIZE_UNIT_EB\x10\x07\x12\x10\n\x0cSIZE_UNIT_ZB\x10\x08*e\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13STATUS_WITHIN_LIMIT\x10\x01\x12\x15\n\x11STATUS_NEAR_LIMIT\x10\x02\x12\x13\n\x0fSTATUS_EXCEEDED\x10\x03\x42\x36Z4github.com/eka-care/proto-contracts/go/vault/recordsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault.storage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/eka-care/proto-contracts/go/vault/records'
  _globals['_SIZEUNIT']._serialized_start=797
  _globals['_SIZEUNIT']._serialized_end=977
  _globals['_STATUS']._serialized_start=979
  _globals['_STATUS']._serialized_end=1080
  _globals['_USAGE']._serialized_start=38
  _globals['_USAGE']._serialized_end=139
  _globals['_EXCEEDED']._serialized_start=141
  _globals['_EXCEEDED']._serialized_end=206
  _globals['_MAXLIMIT']._serialized_start=208
  _globals['_MAXLIMIT']._serialized_end=273
  _globals['_STORAGE']._serialized_start=276
  _globals['_STORAGE']._serialized_end=427
  _globals['_RECORDSSTORAGEDATARESPONSE']._serialized_start=429
  _globals['_RECORDSSTORAGEDATARESPONSE']._serialized_end=498
  _globals['_RECORDSSTORAGEAPIRESPONSE']._serialized_start=501
  _globals['_RECORDSSTORAGEAPIRESPONSE']._serialized_end=794
  _globals['_RECORDSSTORAGEAPIRESPONSE_ERROR']._serialized_start=658
  _globals['_RECORDSSTORAGEAPIRESPONSE_ERROR']._serialized_end=748
  _globals['_RECORDSSTORAGEAPIRESPONSE_ERRORCODE']._serialized_start=750
  _globals['_RECORDSSTORAGEAPIRESPONSE_ERRORCODE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
