// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: vault/identical_docs.proto

package identicaldocs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdenticalDocs represents response for identical documents.
type IdenticalDocs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`                        // List of documents.
	NextToken *string     `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3,oneof" json:"next_token,omitempty"` // Offset for next query.
}

func (x *IdenticalDocs) Reset() {
	*x = IdenticalDocs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_identical_docs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdenticalDocs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdenticalDocs) ProtoMessage() {}

func (x *IdenticalDocs) ProtoReflect() protoreflect.Message {
	mi := &file_vault_identical_docs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdenticalDocs.ProtoReflect.Descriptor instead.
func (*IdenticalDocs) Descriptor() ([]byte, []int) {
	return file_vault_identical_docs_proto_rawDescGZIP(), []int{0}
}

func (x *IdenticalDocs) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *IdenticalDocs) GetNextToken() string {
	if x != nil && x.NextToken != nil {
		return *x.NextToken
	}
	return ""
}

// Document represents each document description.
type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId   string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`       // Document ID.
	DocumentType string `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"` // Type of document.
	Thumbnail    string `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`                           // Thumbnail of the uploaded document.
	Desc         string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`                                     // Description of the uploaded document.
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_identical_docs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_vault_identical_docs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_vault_identical_docs_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Document) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *Document) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Document) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// ListIdenticalDocs respresents listing of duplicate docs in paginated format.
type ListIdenticalDocs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []*IdenticalDocument `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"` // List of documents.
	Offset    *string              `protobuf:"bytes,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"` // Offset for next query.
}

func (x *ListIdenticalDocs) Reset() {
	*x = ListIdenticalDocs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_identical_docs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIdenticalDocs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdenticalDocs) ProtoMessage() {}

func (x *ListIdenticalDocs) ProtoReflect() protoreflect.Message {
	mi := &file_vault_identical_docs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdenticalDocs.ProtoReflect.Descriptor instead.
func (*ListIdenticalDocs) Descriptor() ([]byte, []int) {
	return file_vault_identical_docs_proto_rawDescGZIP(), []int{2}
}

func (x *ListIdenticalDocs) GetDocuments() []*IdenticalDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListIdenticalDocs) GetOffset() string {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return ""
}

// IdenticalDocument represents individual duplicate document set.
type IdenticalDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // MD5 hash of the identical documents.
	Count string `protobuf:"bytes,2,opt,name=count,proto3" json:"count,omitempty"` // Count of duplicates for given MD5.
}

func (x *IdenticalDocument) Reset() {
	*x = IdenticalDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vault_identical_docs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdenticalDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdenticalDocument) ProtoMessage() {}

func (x *IdenticalDocument) ProtoReflect() protoreflect.Message {
	mi := &file_vault_identical_docs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdenticalDocument.ProtoReflect.Descriptor instead.
func (*IdenticalDocument) Descriptor() ([]byte, []int) {
	return file_vault_identical_docs_proto_rawDescGZIP(), []int{3}
}

func (x *IdenticalDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdenticalDocument) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

var File_vault_identical_docs_proto protoreflect.FileDescriptor

var file_vault_identical_docs_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x6c, 0x5f, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x6f,
	0x63, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x44, 0x6f, 0x63, 0x73, 0x12, 0x3c, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x22, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d,
	0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x82, 0x01, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x73,
	0x12, 0x45, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22,
	0x39, 0x0a, 0x11, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6b, 0x61, 0x2d, 0x63, 0x61, 0x72,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x64, 0x6f, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vault_identical_docs_proto_rawDescOnce sync.Once
	file_vault_identical_docs_proto_rawDescData = file_vault_identical_docs_proto_rawDesc
)

func file_vault_identical_docs_proto_rawDescGZIP() []byte {
	file_vault_identical_docs_proto_rawDescOnce.Do(func() {
		file_vault_identical_docs_proto_rawDescData = protoimpl.X.CompressGZIP(file_vault_identical_docs_proto_rawDescData)
	})
	return file_vault_identical_docs_proto_rawDescData
}

var file_vault_identical_docs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vault_identical_docs_proto_goTypes = []interface{}{
	(*IdenticalDocs)(nil),     // 0: vault.identical_docs.IdenticalDocs
	(*Document)(nil),          // 1: vault.identical_docs.Document
	(*ListIdenticalDocs)(nil), // 2: vault.identical_docs.ListIdenticalDocs
	(*IdenticalDocument)(nil), // 3: vault.identical_docs.IdenticalDocument
}
var file_vault_identical_docs_proto_depIdxs = []int32{
	1, // 0: vault.identical_docs.IdenticalDocs.documents:type_name -> vault.identical_docs.Document
	3, // 1: vault.identical_docs.ListIdenticalDocs.documents:type_name -> vault.identical_docs.IdenticalDocument
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vault_identical_docs_proto_init() }
func file_vault_identical_docs_proto_init() {
	if File_vault_identical_docs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vault_identical_docs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdenticalDocs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_identical_docs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_identical_docs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIdenticalDocs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vault_identical_docs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdenticalDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vault_identical_docs_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_vault_identical_docs_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vault_identical_docs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vault_identical_docs_proto_goTypes,
		DependencyIndexes: file_vault_identical_docs_proto_depIdxs,
		MessageInfos:      file_vault_identical_docs_proto_msgTypes,
	}.Build()
	File_vault_identical_docs_proto = out.File
	file_vault_identical_docs_proto_rawDesc = nil
	file_vault_identical_docs_proto_goTypes = nil
	file_vault_identical_docs_proto_depIdxs = nil
}
